### ISSUE TITLE
It is possible change region of existing app?

### ISSUE THREAD

**Issue by sp0033212000** [aws-amplify/amplify-console#1011]
** Please describe which feature you have a question about? **
I want move my amplify app to another region, may I achieve this case?

** Provide additional details**

**Comment by hsspain** [comment]
@sp0033212000 At this time it is not possible to move an Amplify app to another region.

You could use CloudFormation to define your Amplify Console infrastructure so that it is easily replicable across accounts and regions. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Amplify.html
