### ISSUE TITLE
Domain activation is Failed - One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution.

### ISSUE THREAD

**Issue by butoramatus** [aws-amplify/amplify-console#1049]
**App Id**: d1ek1qbwqtobe9
**Region**: eu-central-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
First time I added my custom domain to the amplify app it was working fine. Then I wanted to make changes and I have deleted the custom domain. Since then I am not able to add my custom domain back. I have no other cloudfront distributions. In other Issue I found: "Annoyingly there's a certificate from my old app, that I can't delete for this reason. It responds saying I need to remove the association before removing the certificate." in #1035. Is there a way you can remove all the records of my past distributions?

**Comment by ganipcanot** [comment]
Looks like this app has since been deleted - moving to resolved.

**If you are still experiencing issues you can try following these steps:**

- Is this domain connected to a different Amplify App that you own? If so, make sure you are not trying to reuse one of the hostnames.
- If you are using www.domain.com on the other app, you cannot use www.domain.com on this app
- You can use other hostnames, like blog.domain.com
- If you had this domain successfully connected to Amplify and then recently (within the last hour) deleted it, please wait and try again.
- Check the Cloudfront console to see if you have this domain deployed to any distributions
- If you are positive no CloudFront distribution exists (including in other accounts) using this domain, and only if it would not be disruptive to any currently running services, try deleting and recreating the hosted zone
