### ISSUE TITLE
Domain activation is Failed - One or more of the CNAMEs you provided are already associated with a different resource

### ISSUE THREAD

**Issue by beto** [aws-amplify/amplify-console#1070]
**App Id**: d1setlyy3u4krt
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: 
there is only one CNAME entry for partner.serviceally.co

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information*

**Comment by niknokseyer** [comment]
Were you able to get yours resolved? @beto

**Comment by ganipcanot** [comment]
Looks like this appId has since been deleted.  Going to resolve this ticket.

**If you are still experiencing issues you can try following these steps:**

- Is this domain connected to a different Amplify App that you own? If so, make sure you are not trying to reuse one of the hostnames.
- If you are using www.domain.com on the other app, you cannot use www.domain.com on this app
- You can use other hostnames, like blog.domain.com
- If you had this domain successfully connected to Amplify and then recently (within the last hour) deleted it, please wait and try again.
- Check the Cloudfront console to see if you have this domain deployed to any distributions
- If you are positive no CloudFront distribution exists (including in other accounts) using this domain, and only if it would not be disruptive to any currently running services, try deleting and recreating the hosted zone
