### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by bwinkers** [aws-amplify/amplify-console#1093]
**App Id**: d34q829q80y1ix
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.
I cannot add izzup.com as a custom domain.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.
![image](https://user-images.githubusercontent.com/4514677/94384546-b34ca980-00f7-11eb-93be-2ab274f76f2d.png)

**Comment by bwinkers** [comment]
The domain is hosted in the same account as amplify and I see the DNS records

**Comment by bwinkers** [comment]
![image](https://user-images.githubusercontent.com/4514677/94385749-c14ff980-00fa-11eb-8b21-ddfc058d92b1.png)
This is the error after very attempt

**Comment by Vaaljan** [comment]
I Have the same issue!  Super annoying!

**Comment by bwinkers** [comment]
Any updates? This seems to affect many people.
Could you include the offending hostmnames in the error so we could take action?
I'm not seeing what might be a duplicate, if it exists its becasue anotehr AWS service created it or required that I create it.

**Comment by bwinkers** [comment]
STILL no updates. This is an AWS hosted domain so the issue is 100% in the AWS court.
This is not EASY setup, it doesn't even seem possible.

![image](https://user-images.githubusercontent.com/4514677/94769679-7981da00-0367-11eb-9ab4-1778a89986ef.png)

**Comment by Vaaljan** [comment]
@bwinkers I had to delete the domain, configure it again and make sure on the first step you go the actions -> View DNS records and add that as soon as possible then it should get activated. Once it fails you have to start over. A waste of time.

**Comment by ganipcanot** [comment]
Looks like this app has since been deleted - resolving for now.  If you're still experiencing issues you can re-open the ticket.

**Otherwise you can try following these steps:**

- Is this domain connected to a different Amplify App that you own? If so, make sure you are not trying to reuse one of the hostnames.
- If you are using www.domain.com on the other app, you cannot use www.domain.com on this app
- You can use other hostnames, like blog.domain.com
- If you had this domain successfully connected to Amplify and then recently (within the last hour) deleted it, please wait and try again.
- Check the Cloudfront console to see if you have this domain deployed to any distributions
- If you are positive no CloudFront distribution exists (including in other accounts) using this domain, and only if it would not be disruptive to any currently running services, try deleting and recreating the hosted zone
