### ISSUE TITLE
Trigger a re-build without having any new commits

### ISSUE THREAD

**Issue by dessskris** [aws-amplify/amplify-console#1140]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have changed my build settings or environment variable, and need to rebuild my Amplify app, but I can't. There's no manual build trigger. I have tried setting up a webhook and triggering that, but it cancels my rebuild because it detects no changes in the repo (but what about changes in the build settings and env variable??). So I have to make a random change in my app, commit and push that just to trigger a rebuild.

**Describe the solution you'd like**
Either a manual build trigger option that doesn't cancel itself just because the repo hasn't changed, or an option or question to ask if we want to rebuild upon updating an environment variable or the build script.

**Additional context**
When you don't have any changes in the app but want to change the build script or env variable, and need to rebuild the Amplify app.

**Comment by abhi7cr** [comment]
Hi @dessskris, thanks for the feedback. This is added as a `feature request` to our backlog, and will let you know when we have any updates related to this.

**Comment by swaminator** [comment]
@dessskris are you using a monorepo?

**Comment by dessskris** [comment]
> @dessskris are you using a monorepo?

Yes and the Amplify app has been set up to point to a directory in the monorepo.

**Comment by dmudro** [comment]
This is doable via webhook as you said. Totally works in my React SPA, all I have to do is to fire curl with the webhook endpoint as per doc. The build gets triggered and finishes despite no code change.

_Redeploy this version_ button in build detail should work as well in your case.

Had a similar question some time ago in https://github.com/aws-amplify/amplify-console/issues/929

**Comment by dessskris** [comment]
> This is doable via webhook as you said. Totally works in my React SPA, all I have to do is to fire curl with the webhook endpoint as per doc. The build gets triggered and finishes despite no code change.
> 
> _Redeploy this version_ button in build detail should work as well in your case.
> 
> Had a similar question some time ago in #929

I've just tried that again, yes the webhook triggers the pipeline HOWEVER it does not rebuild the app

It simply says:
`Build cancelled - no diff detected from previous commit`
Even if you've updated the build specs on Amplify or the environment variables.

See screenshot below:

![image](https://user-images.githubusercontent.com/16229203/98124922-b2075d00-1eab-11eb-8f9c-7a2d793abe0f.png)

**Comment by dmudro** [comment]
Strange, works in my case and without needing to change anything in the code. It's just a manual trigger as you would expect. Hopefully someone from the Amplify team will look into this.

I wonder if _Redeploy this version_ could be useful for your case:
![image](https://user-images.githubusercontent.com/1648143/98213338-39ed7580-1f45-11eb-8361-c1f6556089e1.png)

**Comment by dmudro** [comment]
I am now able to replicate the same issue as described by @dessskris 

In addition the Redeploy this version button is gone.

This happened after I converted my application to a monorepo so I understand the context now as indicated [above](https://github.com/aws-amplify/amplify-console/issues/1140#issuecomment-708622110).

**Comment by dmudro** [comment]
Is there any update on this one please?

**Comment by barmatz** [comment]
Having the same issue. Any updates?

**Comment by pisvthanh** [comment]
Having the same issue. Please help

**Comment by mikelhamer** [comment]
Please add this feature

**Comment by BEDDStatus** [comment]
+1 Please add

**Comment by crowe00** [comment]
+1

**Comment by Rebecca-Christi** [comment]
+ 1

**Comment by choudlet** [comment]
+10000

**Comment by cslogan-red** [comment]
@derz @dessskris we've updated the (previously not very accurate) diff logic that was running only for monorepo apps to be opt-in by default so that it doesn't block your builds when needing to redeploy without any changes, this will allow monorepo apps to use the same provided workaround as non-monorepo apps, which is to create a webhook and hit the webhook via curl to trigger a build without a commit.

Additionally, if you'd like to enable diffing for your frontend build, test, and deploy (regardless of whether your app uses a monorepo or not), you can now optionally set the **AMPLIFY_DIFF_DEPLOY** environment variable to `true`, and it will run a diff on your monorepo's `appRoot` by default, if there are no changes in the most recent commit in this folder, the frontend build, test, and deploy steps will be skipped. (We have a fast-follow already coming shortly on this that supports diffing all commits since your most recent deploy for changes instead of just the most recent commit)  Again, to keep the diff logic non-blocking, it is now opt-in via this environment variable, and you can remove the variable or set its value to `false` to bypass the diff logic at any time. See more details in the [docs](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#enable-diff-deploy).

**Comment by derz** [comment]
@cslogan-red amazing, thanks for the feedback and the fix - you've saved us quite a bit of work & headache! ;-) I can confirm that it works as expected now.

**Comment by zhoub** [comment]
+999

**Comment by zhoub** [comment]
+999999

**Comment by crow7m** [comment]
+++++9999999

**Comment by six0h** [comment]
+999

**Comment by Ddevon** [comment]
+1

**Comment by agent-reed** [comment]
+420

**Comment by daniele-sarnari-blinkoo** [comment]
+2022

**Comment by natBizitza** [comment]
+1000000

**Comment by aktoriukas** [comment]
How is this not a feature??? so now if I need to update my ENV variables, which are not working correctly with REACT and require rebuilding, I can't do it without pushing any changes ?? CRAZY.

**Comment by daniele-sarnari-blinkoo** [comment]
> How is this not a feature??? so now if I need to update my ENV variables, which are not working correctly with REACT and require rebuilding, I can't do it without pushing any changes ?? CRAZY.

Feel you
