### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by sanjeetiitr** [aws-amplify/amplify-console#1226]
**App Id**: d3j2z1g8shkddr
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I had already an active CloudFront distribution and Route53 setup for my domain.
Earlier my static website was hosted from S3 and not I am using Amplify.
I disabled the existing distribution and removed all CNAME and A records and then initiated the amplify add domain. And i am getting this error.

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**

![image](https://user-images.githubusercontent.com/13379529/99139849-6d758180-2662-11eb-8c54-c1d409d9038f.png)

**Comment by nimacks** [comment]
Refer to our documentation to troubleshoot domain setup.

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by kahdojay** [comment]
@sanjeetiitr this can happen even if you've deleted the CNAME record from your DNS provider if the name is still associated with an existing cloudfront distribution, or if not enough time has passed since the removal. I just checked your app and both your www and root domain seem to be working now though, so I'll close this but feel free to reopen if you're still having issues.

**Comment by sanjeetiitr** [comment]
Thanks @kahdojay . It worked after removing all existing CloudFront distribution.
