### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by KyleShelton** [aws-amplify/amplify-console#129]
**App Id**: d224g6xdfccjtl
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 
One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.
I have the domain registered through a third party, but I added a hosted zone on route 53 and pointed its nameservers at the domain.

**Comment by nimacks** [comment]
Hi @KyleShelton, according to our records the app associated with d224g6xdfccjtl no longer exists. Did you re-create the app? Have you got it working? Please provide an update so we can assist you to get this working.

**Comment by KyleShelton** [comment]
Hello, I did recreate the app. I'm not sure how to get the proper id for it
but I still haven't got this to work yet.

**Comment by KyleShelton** [comment]
Ah ok, I found the app ARN for the current app I am having issues with.
arn:aws:amplify:us-east-2:437527792999:apps/d23v93pcqul8jg

**Comment by nimacks** [comment]
@KyleShelton, it looks you've already used this domain with another amplify app you created in the us-east-1 region. In order to use this custom domain with your app in us-east-2 you'll need to remove the association from the first app. You cannot use one domain with different apps.

Next Steps:

- Switch to the us-east-1 region in the aws console
- Go into the Amplify console and find the app you already created. 
- Determine if you still want to keep this app associated with the domain.

**Comment by KyleShelton** [comment]
Oh, thank you so much. I didn't even notice that I had switched regions.
That makes so much sense now. This solved my issue.
