### ISSUE TITLE
Amplify Publish Error

### ISSUE THREAD

**Issue by tiago165** [aws-amplify/amplify-console#1411]
I am unable to publish any Amplify project. I also tried with simple apps and get the same issue. I thought it was IAM issue and tried "amplify configure", created new IAM user, gave all admin permissions and the permissions documented here. I also tested the "amplify:ListJobs" policy and it is allowed but still facing the same issue. Unable to develop anything on Amplify.

Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
An error occurred during the publish operation: User: arn:aws:sts::033870858721:assumed-role/us-east-2_HsLadv6Y1_Full-access/amplifyadmin is not authorized to perform: amplify:ListJobs on resource: arn:aws:amplify:us-east-2:033870858721:apps/d2doxkl2ny58tj/branches/staging/jobs/*

**Comment by tiago165** [comment]
I solved the problem using this command:  `amplify configure project`

Got this trick from #1369

**Comment by tiago165** [comment]
I solved the problem using this command:  `amplify configure project`

Got this trick from #1369

**Comment by notpresleybutelvis** [comment]
I think the error pops up because the role is an assumed role, it may have not been configured to do publish due to a bug. Here is a workaround for this
Run 
amplify configure project
select the first option
? Which setting do you want to configure? AWS Profile setting 
? Do you want to set the project level configuration Yes
? Select the authentication method you want to use: AWS profile
? Please choose the profile you want to use <select the profile stored on your system>
amplify publish will then work

Thanks to @tiago165 and [#1369 ](#1369 )
