### ISSUE TITLE
Issue publishing with amplify

### ISSUE THREAD

**Issue by arrashju** [aws-amplify/amplify-console#1422]
**Describe the bug**
When running amplify publish, I get an error at the very end saying the following

An error occurred during the publish operation: User: arn:aws:sts::591601383277:assumed-role/us-east-2_jOn7uQB2e_Full-access/amplifyadmin is not authorized to perform: amplify:ListJobs on resource: arn:aws:amplify:us-east-2:591601383277:apps/dchm1b7sa3ivb/branches/staging/jobs/*

**To Reproduce**
1. Go to console
2. Run 'amplify configure'
3. Configure everything default
4. Update security keys in env variables
5. Run 'amplify publish'

**Expected behavior**
Amplify will get updated with current project

**Screenshots**
<img width="562" alt="Screen Shot 2021-01-03 at 10 30 18 AM" src="https://user-images.githubusercontent.com/10902802/103482438-f1b8cb00-4dae-11eb-964f-4c8095554af2.png">

**Comment by uncodable** [comment]
You need to give your IAM user the Amplify policy (there's a default one by AWS)

**Comment by arrashju** [comment]
I checked every policy checkbox when creating the user after running 'amplify configure'

I get a different error now though

**Comment by arrashju** [comment]
I solved the issue by deleting the out folder for Next.js and seeing why it wasn't updating. It wasn't updating because my package.json didn't have the next export part of "build": "next build && next export". After that I updated my Git repository and it automatically updated amplify and the website is now updated and works!

My project was being deployed from my Git repository. I think that's why it wouldn't let me run 'amplify publish'.

**Comment by notpresleybutelvis** [comment]
I think the error pops up because the role is an assumed role, it may have not been configured to do publish due to a bug. Here is a workaround for this
Run 
amplify configure project
select the first option
? Which setting do you want to configure? AWS Profile setting 
? Do you want to set the project level configuration Yes
? Select the authentication method you want to use: AWS profile
? Please choose the profile you want to use <select the profile stored on your system>
amplify publish will then work

Thanks to @tiago165 and [#1369 ](#1369 )
