### ISSUE TITLE
Incoming webhook visibility in Amplify Console

### ISSUE THREAD

**Issue by niraj8** [aws-amplify/amplify-console#1467]
** Please describe which feature you have a question about? **
Amplify app connected to Github repo uses an incoming webhook to get notified of push event
<img width="478" alt="Webhooks" src="https://user-images.githubusercontent.com/8666468/104999523-005fdd00-5a53-11eb-9aa3-bff80653a39b.png">

This incoming webhook is not visible in the Amplify Console > App > Build Settings.
Is this the expected behavior?

** Provide additional details**
Same thing happens when creating an app using a CloudFormation template

**Comment by hsspain** [comment]
@niraj8 Yes, this is expected behavior. We use those webhooks to automatically start builds of your apps when changes are made to the code in the repository. When an app is "connected" to a repository, these webhooks are created.

I am closing this ticket, but please feel free to re-open if you have further questions/issues.

**Comment by niraj8** [comment]
Opening this again.
I understand the usage of the webhook.
Can you comment on this, please?
> This incoming webhook is not visible in the Amplify Console > App > Build Settings.

**Comment by hsspain** [comment]
@niraj8 The incoming webhooks listed under App > Build Settings are additional webhooks that can be created outside of the integration with source control. The source control integrated webhooks will not be listed here.
