### ISSUE TITLE
Can't create new app

### ISSUE THREAD

**Issue by mmellado** [aws-amplify/amplify-console#149]
**Describe the bug**
I am trying to create a new app from a repository in CodeCommit. When I configure the environment variables I get a 500 response with an error that won't let me create a new app. We already have 9 other apps working with this repository.

**To Reproduce**
1. Go to AWS Amplify console
2. Click on Connect App
3. Select the CodeCommit option
4. Select project and master branch 
5. Enter environment variables
6. Click create

**Expected behavior**
New app should be created

**Additional context**
JS Console returns 500 error and GUI shows the message:

>>> Houston, there's a problem
Oops, something went wrong. Please try again later.

**Comment by swaminator** [comment]
@mmellado unable to reproduce the issue. Is this repeatable for you?

**Comment by mmellado** [comment]
Yes. It seems like AWS is not respecting my amplify apps quota

**Comment by hzhenmin** [comment]
@mmellado This is caused by you have too many triggers in the repo of CodeCommit. It has reached the CodeCommit limit 10. This caused AWS Amplify Console was unable to add new trigger and failed to create app. You can follow this link to delete unused trigger and create the app again.
https://docs.aws.amazon.com/codecommit/latest/userguide/how-to-notify-delete.html

**Comment by grayaii** [comment]
We don't use triggers to trigger builds. 
We use webhooks to trigger builds.
We cannot delete any of our 10 triggers.
Can we create an Amplify project that uses webhooks instead of triggers?

The alternative is to delete a trigger, create the amplify project, then DELETE the trigger that amplify created (since we are not using it at all), re-add the original trigger that we deleted, and then use web hooks to trigger the amplify projects.
