### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by idrico** [aws-amplify/amplify-console#1559]
**App Id**: d2isl1kzqnazyo
**Region**: us-east-2
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by JawadBish** [comment]
Hi,
Im facing the same issue, SSL certification is running for long time, without any error message.
Please see below message I have :  
"In order to verify domain ownership, configure the following CNAME record associated with your domain and verify that the CNAME record exists in your Domain Name Server (DNS) file."
I can see that in Route53 - records are created successfully. 
please assist.
Thanks in advance.
