### ISSUE TITLE
Amplify console generated reactjs app url not working

### ISSUE THREAD

**Issue by karthik2872** [aws-amplify/amplify-console#1580]
**Describe the bug**

Amplify Console, US-East-1 N.Virginia region , get this error

**This main.d32wlvp146067e.amplifyapp.com page can’t be found**

Simple steps followed to generate a basic react app through amplify console and github, changes to app.js are getting deployed from Github --> amplifyapp but url above is not reachable

**To Reproduce**
1. Go to 'amplify console'
2. Click on 'All Apps'
3. Click on specific app --> Front end environment TAB --> this url generated https://main.d32wlvp146067e.amplifyapp.com
4. See error --> when clicked shows https://main.d32wlvp146067e.amplifyapp.com - page not found http 404 wh

**Expected behavior**

https://main.d32wlvp146067e.amplifyapp.com expected to show the basic simple react app page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ios
 - Browser chrome
 - Version 78.0.3904.97

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kahdojay** [comment]
@karthik2872 it looks like your app code is nested in a top level folder preventing us from autogenerating the proper build commands. (You can tell because your build spec commands are empty and there is a warning asking you to confirm your build output directory). If you move your application code out of the nested folder and confirm the buildspec looks correct before deploying it should work.

Closing this for now, let us know if you run into any further issues.
