### ISSUE TITLE
How to find ip for ANAME?

### ISSUE THREAD

**Issue by krllgranin** [aws-amplify/amplify-console#1589]
**App Id**: d89pw352hbn04
**Region**:eu-central-1
**Step**:
**Status**: Available

**Issue/question**
1. I use the reg.ru registration domain. And I cant add ANAME record. Because reg.ru need ip, but I have only domain not ip. Domain from the amplify instruction also unavailable. How can I find his ip?
2. And do I need to change DNS-servers? Now it sets ns1.reg.ru, ns2.reg.ru.

**Error message**
Can't access the site

**Comment by krllgranin** [comment]
I cheked domain by servis https://2ip.ru/whois/. And every time it shows different ip.

**Comment by siegerts** [comment]
Hi @krllgranin , have you tried making Amazon Route 53 the DNS service for the existing domain?

That is the recommended approach when a provider doesn’t support ANAME/ALIAS records. For these providers, we strongly recommend migrating your zone file to Amazon Route53 to account for this (below) or possibly transferring to another host that does allow for this. Given the current limitations, I think that it makes sense to investigate a migration to Route 53 or other.

- https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-a-third-party-dns-provider.html
- https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/MigratingDNS.html.

There isn't a single dedicated IP for your app that you can point to since it is a Cloudfront distribution and is a globally distributed by nature (i.e. requests are routed via DNS based on location of access and the IPs may always be changing, etc.).
