### ISSUE TITLE
<id>.cloudfront.net domain activation - returns 404

### ISSUE THREAD

**Issue by evandegr** [aws-amplify/amplify-console#1677]
**App Id**: d18a38ve9o5yls
**Region**: us-east-2
**Step**: Configure DNS settings
**Status**: Domain activation

**Issue/question**
d38qr63xn9qqf1.cloudfront.net is returning a 404. I've tried to set things up twice and both times the cloudfront URL just 404s.  I'm trying to connect AWS amplify to my GoDaddy domain.  I've added 2 CNAMEs in Godaddy:

CNAME `mysite.com` pointing to `d38qr63xn9qqf1.cloudfront.net`
as well as my SSL configuration which seems to be successful.

Am I missing something here?  The cloudfront URLs shouldn't just 404 right?

**Comment by ganipcanot** [comment]
You have an app for `d18a38ve9o5yls` the custom domain is a separate Cloudfront distribution against `d38qr63xn9qqf1`.

Hitting `d38qr63xn9qqf1.cloudfront.net` will not work because Amplify removes that as a valid CNAME on the CF distribution (Amplify manages all the Cloudfront distributions in our service accounts - and not your AWS account)

In other words (in your specific case) - the CF distribution for the custom domain only has 2 cnames:
1. `mysite.com`
2. `www.mysite.com`

I.E. it does not contain the default of `d38qr63xn9qqf1.cloudfront.net` so that will not work - but your custom domains that you setup `mysite.com` and `www.mysite.com` would.

Closing for now - please re-open if you have additional questions or concerns.
