### ISSUE TITLE
Domain activation is Failed - CNAME associated with a different resource, except they are not

### ISSUE THREAD

**Issue by ngtrunghuan** [aws-amplify/amplify-console#172]
**App Id**: d2vzuf12a4h8lg
**Region**: ap-southeast-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I configured my GoDaddy domain thisishuan.com to my amplify app. I have done the steps as mentioned here but still couldn't figure out how to resolve:
https://read.acloud.guru/how-to-deploy-a-custom-domain-with-the-amplify-console-a884b6a3c0fc

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by aromka** [comment]
I get the same for all Route53 domains - any fix for this?
Don't have any CNAMEs for the subdomains i'm trying to use

**Comment by cslogan-red** [comment]
@ngtrunghuan it doesn't appear that your CNAME records resolve using whatsmydns.net for thisishuan.com, you can follow the documentation below to make sure you've completed configuring your CNAME records with your DNS provider (GoDaddy):

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-third-party

Additionally, if your provider is GoDaddy, they don't support ANAME/ALIAS records, so you'll have to do some additional configuration as outlined here:

https://docs.aws.amazon.com/amplify/latest/userguide/howto-third-party-domains.html

@aromka your issue is separate, if you can post your domain(s)/app Id'(s) that you're encountering this with I can take a look, thanks!

**Comment by ngtrunghuan** [comment]
@cslogan-red hey Chase, thanks for the response. I think what happened was:
- I initially wanted to use a S3 bucket + CloudFront to host my static site.
- I configured the CNAMEs to point to the S3 bucket addresses.
- I changed my mind and wanted to use Amplify + Route53 instead
I think it took some time for the entire S3 + CloudFront setup to be completely clean. I tried again after 2-3 days and everything is working now.
