### ISSUE TITLE
How do I retry a build? Retry button has disappeared after updating config for monorepos

### ISSUE THREAD

**Issue by rawbeans** [aws-amplify/amplify-console#1727]
I used to be able to retry a failed build by clicking the retry button next to "View build history" in the top right of the latest build. This button recently disappeared, around the time I updated my config to have monorepo support.

Currently my only mechanism of retrying a build, is to make another commit to trigger a new build.

Why did this button go away and are there any other ways I can retry the build?

**Comment by siegerts** [comment]
Hi @rawbeans , sorry to hear. If there are any screen shots of what the UI looks like (where the button should be, etc), that'd be helpful to see. Also, what browser are you using?

Also, I'd also recommend trying a hard refresh of the browser too :) Sometimes, that helps.

**Comment by rawbeans** [comment]
I just tried a hard refresh and update of Chrome, as well as Safari and Firefox, all with the same result. This is what I am seeing in the screenshot below.

![image](https://user-images.githubusercontent.com/810878/113905109-a6380380-9787-11eb-994b-a3757169a0e1.png)

**Comment by swaminator** [comment]
@rawbeans the monorepo workflow currently doesn't have the 'retry' button. You have to manually kickoff another build. We are working on adding it back for monorepos.

**Comment by rawbeans** [comment]
Thanks for the update. Any help on the second part of my question: 

> are there any other ways I can retry the build?

By "manually kick off another build" are you referring to making another commit?

**Comment by siegerts** [comment]
Hi @rawbeans , Yes, currently, you can trigger a redeploy by adding and pushing a commit or by possibly setting up your own [webhook](https://docs.aws.amazon.com/amplify/latest/userguide/webhooks.html) to trigger as part of a process.

**Comment by jfernandomeyer** [comment]
Hi @siegerts. Just as a follow-up to your suggestion, the only way right now to actually re-trigger a pipeline is to push a new commit.

Both Webhooks and triggers via AWS CLI actually abort the pipeline in the build steps saying nothing has changed.

See the steps I've done to validate that:

- Push changes to a given branch per environment (staging, and production for example)
- Pipelines are triggered. Build job fails because any given reason
- No way to retry from the interface
- I tried webhooks. The same happens. It says there are no new commits
- I tried AWS CLI call also didn't work. It aborted the build as there are no new commits

Do you have an idea about when the retry feature would be enabled?
Thanks 🙏

**Comment by mathvbarone** [comment]
I am also facing the same issue, is quite annoying to push so many dummy comments, every time the pipeline fails.

**Comment by swaminator** [comment]
@mathvbarone @jfernandomeyer we are fixing this soon.

**Comment by swaminator** [comment]
@mathvbarone @jfernandomeyer you can set an `AMPLIFY_DIFF_DEPLOY` environment variable to a value of `false` to disable the diff logic behavior.

**Comment by cslogan-red** [comment]
@rawbeans @mathvbarone @jfernandomeyer we've updated the (previously not very accurate) diff logic that was running only for monorepo apps to be opt-in by default so that it doesn't block your builds when needing to redeploy without any changes, this will allow monorepo apps to use the same provided workaround as non-monorepo apps, which is to create a webhook and hit the webhook via curl to trigger a build without a commit.

Additionally, if you'd like to enable diffing for your frontend build, test, and deploy (regardless of whether your app uses a monorepo or not), you can now optionally set the **AMPLIFY_DIFF_DEPLOY** environment variable to `true`, and it will run a diff on your monorepo's `appRoot` by default, if there are no changes in the most recent commit in this folder, the frontend build, test, and deploy steps will be skipped. (We have a fast-follow already coming shortly on this that supports diffing all commits since your most recent deploy for changes instead of just the most recent commit)  Again, to keep the diff logic non-blocking, it is now opt-in via this environment variable, and you can remove the variable or set its value to `false` to bypass the diff logic at any time. See more details in the [docs](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#enable-diff-deploy).

**Comment by swaminator** [comment]
Just to follow up on @cslogan-red's comment above, you can setup a webhook to trigger a build now without doing anything. We are working on adding the retry button back to the console.

**Comment by siegerts** [comment]
Closing as this feature is now implemented and docs are linked above.

**Comment by jfernandomeyer** [comment]
Hey @siegerts. Just one question, is the issue to add the retry button a different one?

Thanks for the support 🙏

**Comment by siegerts** [comment]
@ferdingler, good catch! :) Reopening for tracking towards the addition of the button! (Thought there was another req opened for that 🤦🏻 )

**Comment by siegerts** [comment]
https://github.com/aws-amplify/amplify-console/issues/1247

**Comment by victorccccc** [comment]
Hi, We've updated the monorepo feature, and you can see `Redeploy this version` button for Monorepo Apps now
