### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by antoinedelorme** [aws-amplify/amplify-console#1764]
**App Id**: d2228lahp14x8z
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I am trying to activate a third party (Google domain) with my amplify app.  It is failing on the last stage and it looks like the problem is on AWS side  as when I try to open my webpage with the google domain url I have the following message:

403 ERROR

The request could not be satisfied.

Bad request. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner. 
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation. 

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.
<img width="1062" alt="Capture d’écran 2021-04-22 à 08 51 17" src="https://user-images.githubusercontent.com/19636972/115669633-c4d1f900-a348-11eb-8741-1bfd5e567f47.png">
<img width="1027" alt="Capture d’écran 2021-04-22 à 08 50 19" src="https://user-images.githubusercontent.com/19636972/115669302-66a51600-a348-11eb-8e31-92d72fc831f6.png">

**Comment by antoinedelorme** [comment]
Thank you. I had been through the guide.
I have used whatsmydns.net, and the CNAME is resolving fine
What is the next step?

**Comment by ferdingler** [comment]
Hi @antoinedelorme, your CNAME records look correct as you described. However it seems like the activation failed because your domain name is already being used in another CloudFront distribution. Take a look at the following links to troubleshoot this issue. 

1: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error

2: https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error
