### ISSUE TITLE
Domain activation is Failed - One or more of the CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by harzulu** [aws-amplify/amplify-console#1806]
**App Id**: dvbataxo7dll
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 

"One or more of the CNAMEs you provided are already associated with a different resource."

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

There are no CNAME records when I start the custom domain connection, and after it starts only the aws records (two CNAME records and one A record) all 3 auto-generated by aws. And If i remove the CNAME record, not for our domain name with www., it still doesn't work.

**Comment by harzulu** [comment]
I have tried to go through every resource and tutorial I can find and nothing is able to help solve this issue

**Comment by ferdingler** [comment]
Hi @harzulu , the error of CNAME is already associated with a different resource is likely because another CloudFront distribution is already using the domain name you are trying to associate to Amplify. We have documented troubleshooting steps on this FAQ about this: https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md#cnamealreadyexistsexception . 

Can you check it out and update us back with results? Thanks
