### ISSUE TITLE
Domain activation is Failed - Recreating domain failing

### ISSUE THREAD

**Issue by jingo64** [aws-amplify/amplify-console#1838]
**App Id**: d1pwgea1m2idtd
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I want to add a second CNAME (www, as well as alpha which we had previously). I couldn't seem to just add a new one, so I deleted the domain and tried to recreate it.

I've tried deleting all of the CNAMES and recreating, but it keeps having this issue

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by ferdingler** [comment]
Hi @jingo64, I see that your domain is already resolving and available with both CNAMEs `www` and `alpha`. I am curious why were you not able to add those CNAMEs the first time you tried it? Was there an error? 

Keep in mind that adding subdomains to a custom domain might take a few minutes because CloudFront needs to propagate those changes across all edge locations globally, so is not immediate that your subdomains will resolve.

**Comment by jingo64** [comment]
hi @ferdingler , so the issue we appeared to have was there was a legacy domain set up in Cloudfront which I was unfamiliar with which was using the `www` domain, which I think caused this issue. I deleted that Cloudfront distribution as it wasn't needed, and since things seem to be working as expected. Thanks for getting back to me!
