### ISSUE TITLE
SSL custom domain not working

### ISSUE THREAD

**Issue by fangzhouli** [aws-amplify/amplify-console#1842]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3k854yawandhi

### Region

us-west-2

### Step

Domain management

### Status

Available

### Issue or question

Despite the fact that my "Domain management" is showing that domain status "Available", it does not open the webpage.

### Error message

"This site can't be reached"

took too long to respond.

**Comment by ferdingler** [comment]
Hello @fangzhouli, I think the problem is that you configured the subdomain to be a wildcard `*` and we currently don't support wildcard subdomains in Amplify. We have a feature request open here: https://github.com/aws-amplify/amplify-console/issues/44 that you can +1 if this is something you are interested in. 

To fix your custom domain, you'll need to define a proper subdomain like `www` on your custom domain. Let us know if this helps resolve your issue.

**Comment by fangzhouli** [comment]
@ferdingler Thank you so much, adding "www" completely resolved the issue. Have a wonderful day!!!!
