### ISSUE TITLE
SSL configuration is Running - Facing issue with hosting domain

### ISSUE THREAD

**Issue by manoj10101996** [aws-amplify/amplify-console#1878]
**App Id**: d35gowt52nggah
**Region**: us-east-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I am trying to host my amplify app with the domain which is buyed on Google  domains. 

I have tried all the documentation and ways but still not able to host my website

please help me to resolve.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by nimacks** [comment]
@manoj10101996  since your domain is registered with Google domains, can you confirm that you've updated CNAME settings per this documentation https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#my-domain-hosted-with-a-third-party-is-stuck-in-the-pending-verification-state?

**Comment by nimacks** [comment]
Our records indicate that you've deleted this app. Re-open if you're still having issues.
