### ISSUE TITLE
Domain activation is Failed - One or more aliases specified for the distribution

### ISSUE THREAD

**Issue by germain-receeve** [aws-amplify/amplify-console#1884]
**App Id**: d3ccg41ngjf9sa
**Region**: eu-central-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Hello dear AWS support!
We are facing a domain activation issue with one of our customer, for a 3rd party domain they manage.
It seems like some DNS config might need change but it's not said what values they should use, can you help use finding which cloudfront URL they need to register for the CNAME?

**Error message**
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem

**Comment by receeveBackes** [comment]
Any help here would be appreciated. It was verified and green before, and it just changed at some point. Plus, it's not possible in the console to view the DNS entries to make a quick comparison because the menu option is greyed out (and if for some reason it is changed, we can't copy out the new one).

**Comment by receeveBackes** [comment]
Following up here because nothing has been commented. What we also can't find in the documentation is why the cloudfront distribution would change (i.e. the CNAME entry). Are there particular triggers that cause it to happen? We had swapped out the subdomain under the TLD, but the initial setup did work. If there are particular changes that results in the Cloudfront part changing, then we need to know where to find that so that we are not going through this again in a live production situation. 
Thanks!

**Comment by receeveBackes** [comment]
Hi @nimacks, yes, exactly. We couldn't see the DNS entry (CNAME) anymore. We had it fine 5 months ago, then we were checking a few things and it was red, and the error was the CNAME was wrong. So in order to try and fix it, we removed and recreated it, in order to get the menu option to become available in order to then replace the DNS entry. We still don't know why it suddenly changed prior to that. 

In the meantime, there is a second domain that hit the same status. It did the same thing. Created, we put in the DNS, and now it's failed. The first one in a weird way is kind of working. This new one is not.

**Comment by receeveBackes** [comment]
Hi @nimacks, I presume that based upon the number of these, that there is some issue that hasn't been resolved? We actually do need this to work in order to take three customers live at this point, and if Amplify can't do the job, then we will need to switch this setup rather soon. So any feedback or transparency would be appreciated. 

Thanks!

**Comment by nimacks** [comment]
Hi @receeveBackes, apologies for the delay. We are currently working on providing a list of resources  that have conflicting CNAMEs in the console. This will provide you with the necessary information you need to troubleshoot.

**Comment by ferdingler** [comment]
Hi @germain-receeve, I'm sorry you had issues creating your custom domain. We have recently improved our error messaging on the CNAMEAlreadyExistException to give customers better information on how to recover from it. This usually means one of these things: 

1) You have already used the same custom domain in another Amplify App in another region/account. 
2) You are using this domain in another service: LightSail or API Gateway. 
3) Your domain has an old CNAME record that points to a cloudfront.net URL from a previous Amplify App. (This one is probably your usecase) 

Feel free to re-add the custom domain and you should get better information on what's going on. Thanks for reporting!
