### ISSUE TITLE
SSL configuration is Running - Keeps running forever

### ISSUE THREAD

**Issue by cariloapp** [aws-amplify/amplify-console#1913]
**App Id**: d20qo1ulqdu90t
**Region**: us-east-2
**Step**: SSL configuration
**Status**: Running

**Issue/question**
I transferred my domain from GoDaddy to Route53 since then I have been trying to link my Amplify app to the domain name on route53 
when setting up I select the domain name which is on route 53 and it automatically populates the ACM verification and CNAME and ANAME records on route53 

After then I am still stuck at SSL configuration for almost 3 days now 
I have deleted the domain and added it back to no  avail

**Comment by ferdingler** [comment]
Hi @cariloapp, apologies for the delay on this ticket. This sounds like the NS records were probably not transferred properly from GoDaddy to Route53. Because if Amplify was able to add the ACM verification record and CNAME records on your hosted zone, but they were still not resolving to the correct values, it means the domain wasn't really pointing to Route53. 

I know it's been a while since you opened this ticket but I recommend you use dnschecker.org to verify whether your domain is actually resolving any record defined on Route53 even before you add the domain to Amplify. Feel free to re-open this case if you have issues again.
