### ISSUE TITLE
401 http repsonse for webmanifest with Access control settings

### ISSUE THREAD

**Issue by codingnuclei** [aws-amplify/amplify-console#195]
**Describe the bug**
With Access control settings ON (password set):
(once signed in)
- manifest.webmanifest gets a 401. 

- All other resources + bundles download as expected

With Access control settings OFF (password set) 

- manifest.webmanifest downloaded as expected

**To Reproduce**
1. Deploy a PWA with amplify console
2. Enable password via Access control settings
3. Navigate to the PWA url
4. See error: manifest.webmanifest 401

**Expected behavior**
manifest.webmanifest download fine

**Comment by anatonie** [comment]
Hi @codingnuclei 

This is actually caused by CORs configuration, as the browser treats this request as a cross-origin request and as such does not send the necessary credentials.

Adding **crossorigin="use-credentials"** to the link in your **index.html** will fix this issue by telling your browser that this call needs to be made with your authentication credentials.

```
<link crossorigin="use-credentials" rel="manifest" href="./manifest.json" />
```

More information on this can be found here https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes

**Comment by codingnuclei** [comment]
@anatonie thanks, that worked like a charm. Thanks for the response!!
