### ISSUE TITLE
The app is not loading on my 3rd party domain

### ISSUE THREAD

**Issue by Kukindoo** [aws-amplify/amplify-console#2113]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2jovmz0usyk9a

### Region

us-east-1

### Step

After domain activation

### Status

Not loading

### Issue or question

Hi everyone,
I have issue after connecting my domain to my 3rd party domain.
when I run my app as amazon URL it works fine, but when I try to access it by uniqy.hypnos-infinitum.tech it says that it refuses to connect.
Do you know where might be problem?
Domain forwarding?
DNS issue?

Thank you,
Jakub

### Error message

This site can’t be reached
uniqy.hypnos-infinitum.tech refused to connect.

### Additional information

N/A

**Comment by nimacks** [comment]
Hi @Kukindoo, the domain was  configured to a specific CNAME which is `www`. In order to access your domain you have to use this format https://www.uniqy.hypnos-infinitum.tech/. I verified that I could hit the site. 

In the case where you want to access via the root domain, you'll need to ensure that your dns provider supports ANAME records. See this documentation for an example https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-godaddy.html.

Re-open if you have any further questions.
