### ISSUE TITLE
Adding Custom Headers to specific web pages within a single page application

### ISSUE THREAD

**Issue by chadmg** [aws-amplify/amplify-console#2134]
**Please describe which feature you have a question about?**
Custom Headers

**Provide additional details**
I'm trying to configure [Custom Headers](https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.html) on a SPA (single page application) for certain client side routes only in order to [block search engines from indexing](https://developers.google.com/search/docs/advanced/crawling/block-indexing) only those routes:

`X-Robots-Tag: noindex`

Based on my current understanding, the `pattern` field allows you to specify which _file paths_ will use the custom headers, however because we are building a SPA there is no actual file at the client side route that we are trying to prevent from indexing. Is there another solution you would recommend or am I missing something? 

**What AWS Services are you utilizing?**
AWS Amplify

**Provide additional details e.g. code snippets**
Our current setup uses the suggested rewrites for a SPA application:

```
</^[^.]+$\|\.(?!(css\|xml\|gif\|ico\|jpg\|js\|png\|txt\|svg\|woff\|woff2\|ttf\|map\|json\|html)$)([^.]+$)/> | /index.html | 200 (Rewrite)
```

I've tried adding the custom headers as suggested in the docs:
```
 - pattern: '/specific-path/*'
    headers:
      - key: 'X-Robots-Tag'
        value: 'noindex'
```

This seems to have no effect in terms of the custom headers being applied.

**Comment by siegerts** [comment]
Hi @chadmg :wave:

Yes, once the SPA "catches" the request, the subsequent routing is handled by the router in you app. Is it possible to use the meta tag approach instead of the headers?

From the link, `<meta name="robots" content="noindex" />` can be used on each page to have a similar effect. There may be a meta configuration package for the framework that you're using. For example, [Vue Head](https://github.com/ktquez/vue-head) and [React Helmet](https://github.com/nfl/react-helmet) are options for Vue.js and React.js, respectively. 

Also, I'd suggest adding a `robots.txt` - https://developers.google.com/search/docs/advanced/robots/intro.

Hope that this helps.
