### ISSUE TITLE
Get AccessDenied when running the simple GettingStarted app

### ISSUE THREAD

**Issue by lwatawala1953** [aws-amplify/amplify-console#2141]
AWS amplify - 

Build a Basic Web Application - Create a Web App with Amplify Console

I diligently followed the steps described in the getting started tutorial:
https://aws.amazon.com/getting-started/hands-on/build-web-app-s3-lambda-api-gateway-dynamodb/module-one/?e=gs2020&p=build-a-web-app-intro

But, after uploading my zipped up Hello World HTML file (Index.html.zip file from MacBook Pro laptop), then after the deployment was successful, when I click on the Domain link (https://dev.d2gcn3hvtvb3r4.amplifyapp.com), I get the error:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>8XKR4W0Y1TBTTH3G</RequestId>
<HostId>RP5r74ZL8UGqSCRyH6Wgug4Y8UJcJz0ZoaitDV23Ff4VkFvpOaBZrETanAuj25zHM0t9fZp5sbM=</HostId>
</Error>

How Do I correct this error?

**Comment by kahdojay** [comment]
@lwatawala1953 This commonly occurs when one zips the folder rather than the contents of the folder, can you ensure you're doing the latter: https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html

looks like you've deleted your app, feel free to reopen or open a new issue if this is still happening after attempting the above, leaving the app in place so we can investigate further

**Comment by lwatawala1953** [comment]
Sorry I had accidentally deleted the old app. I have created a new app, and have the same issue. I confirm that I zipped just the contents of the folder, in fact just one HTML file of the Hello World example.

The App ARN on the new app I deployed is -  arn:aws:amplify:us-west-2:468629295631:apps/d2er68ihyi9odj
