### ISSUE TITLE
Switching Cloudfront+S3 => Amplify with custom domain requires downtime

### ISSUE THREAD

**Issue by CharlieHawker** [aws-amplify/amplify-console#22]
**Region**: eu-west-2
**Step**: Final Step
**Status**: Common issue across apps

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
This is not an issue with a specific domain, just one we've encountered during the migration of several static sites from S3 bucket + Cloudfront CDN hosting to AWS Amplify.

AWS Amplify persistently fails on the last step of domain activation when the domain is already associated as a cname on another resource (Cloudfront in our case). The only way to resolve this is to seemingly deactivate the cname(s) in Cloudfront, wait for the deployment to complete, then remove and re-add the domain to the chosen Amplify App.

This is far from ideal as it is commonplace for us to migrate our projects from the old S3+Cloudfront setup to Amplify, but this means we *must* have downtime in order for the domain to successfully be transferred over.

**Additional Information**
Route53 is the DNS provider we've been using in all cases.

**Comment by hzhenmin** [comment]
The best process to follow to minimize downtime here would be:
1. In your Amplify Console app, open the domain management screen
2. Type in your root domain (yourdomain.com) and click configure
3. Click “Exclude root” button
4. Click “Remove” button next to the “www” sub domain that was automatically added
5. Click save
What we have now done, is started the process of creating and verifying a domain in Amplify Console, without adding any CNAMEs to the Amplify Console Cloudfront Distribution.
Now follow the instructions for setting up the verification CNAME so that your new custom domain will receive a SSL certificate.
While this process is completing, please check the TTL on the DNS records you are moving to Amplify Console. You want them to be as small as possible so that the change propagates quickly. If you have to change this value, please be sure to wait out at minimum, the original TTL before continuing, to make sure that your new TTL is in effect.
Once that is done and the domain is marked as available, you’re now ready to do the migration.

You will need to do the following in quick succession:
1. Change the DNS record
2. Remove the CNAME from your Cloudfront distribution.
3. Add the CNAME to Amplify Console by going to the domain management page, and clicking “Manage subdomains”
Doing it following this method you should see very little downtime, and will mainly depend on the TTL of the DNS record.

**Comment by CharlieHawker** [comment]
Thanks for the prompt response @swaminator – can you confirm what change you're suggesting is made in "_1. Change the DNS record_" is in the migration steps at the end? 

Surely there's nothing needed on the DNS front at this point if:

- You've already verified the domain via the CNAME verification
- You've not yet removed the CNAME from Cloudfront (step 2)
- You've not yet added the CNAME in Amplify Console (step 3)

**Comment by anatonie** [comment]
Hi @CharlieHawker,

You are correct!
When adding the domain (or at any point after) to Amplify Console, you can add a test sub domain, something you don't use in production/elsewhere. This has 2 benefits:
1. It lets you test your domain and SSL certificate before cutting over traffice
2. Because your custom domain uses a single Cloudfront distribution for all sub domains, you can infer the destinations for the other records.

The other option would be to do the last 3 steps in a slightly different order:
1. Remove the CNAME from your Cloudfront distribution.
2. Add the CNAME to Amplify Console by going to the domain management page, and clicking “Manage subdomains”
3. Change the DNS record

The first and second steps can be done immediately after each other (you do not need to wait for the distribution to say **Available** again), so these two paths should have about the same amount of downtime, but the first one gives you the opportunity to test the site using your custom domain.

Please let me know if you have any other questions!

**Comment by CharlieHawker** [comment]
@anatonie amazing, this helped put the final piece of the puzzle together, thank you 🎉 

Not sure if this issue should remain open? I'm reluctant to close as I feel that the issue I was having could be better explained by the web interface - particularly around offering help if there's a resource already linked to the subdomain you're trying to connect to Amplify.

**Comment by forTomorrow** [comment]
@swaminator i was following same steps as above to move my s3 static website to aws amplify. subdomain is working fine where as actual domain https://example.com not working i am getting site cant be reached error can you able to help me here.

thanks in advance
sam
