### ISSUE TITLE
Unable to manually invalidate cached files in CloudFront

### ISSUE THREAD

**Issue by bobrossthepainter** [aws-amplify/amplify-console#2217]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dmpiihwf1q6nt

### Region

eu-central-1

### Amplify Console feature

Not applicable

### Describe the bug

Hi,
we are running a Next.js SSR build and deployment and want to manually invalidate some parts of the CloudFront Cache on specific (non amplify related) events.
After submitting the invalidation request (either via the CloudFront UI or CLI `aws cloudfront create-invalidation --distribution-id <dist-id> --paths "/*"`), the cache is still there. We evaluated this by the Artifact-Age not being resetted and no CloudFront Miss being reported back. So we thought at first it isn't working, but then we tried accessing the app via the .cloudfront.net url instead of the .amplifyapp.com url to verify if the cache has been dropped and in fact it had. But via the .amplifyapp.com url the cache still persists.

Are there two CloudFronts in place for one Amplify Next.js SSR App? If so, is it possible to manually invalidate files/folders of both caches?

### Expected behavior

When manually triggering a CloudFront cache invalidation of files/folders, their cached state should be invalidated for the .amplifyapp.com domain.

### Reproduction steps

1. Create and Deploy Next.js SSR Amplify App
2. Add some custom-headers in Amplify, for long-lasting cache `public, max-age=0, s-maxage=172800, must-revalidate` or switch to Preformance-Mode
3. Access the same example resource via the .amplifyapp.com and the .cloudfront.net url (with curl -v or other tooling)
4. Invalidate the CloudFront cache for the accessed resource by executing `aws cloudfront create-invalidation --distribution-id <dist-id> --paths "/<path-to-resource>"`
5. Verify the response headers, when once again accessing the resource for the two urls
6. -> .amplifyapp.com still serving the cached data, whereas cloudfront.net serves a fresh version

**Comment by ferdingler** [comment]
Hi @bobrossthepainter, that's correct, there are 2 CloudFront distributions fronting an SSR app. On a deployment, we flush (invalidate) the cache on the distribution deployed on your account. However, if you have enabled Performance Mode or added cache-control headers to increase cache time on your Amplify App, there is no way to invalidate the cache of the managed distribution at the moment. You will need to wait until `s-max-age` expires. Which the maximum you can set is 24 hours precisely so that you are not in a situation of perpetually having something in the cache. 

I hope this helps clarify things and feel free to re-open if you have further questions.
