### ISSUE TITLE
[Next.js SSR] - Use a single stack of resources per application

### ISSUE THREAD

**Issue by quinnturner** [aws-amplify/amplify-console#2272]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

N/A

### Describe the bug

Next.js SSR applications take 8-13 minutes to build and deploy per build. On the other hand, Netlify and Vercel only take a couple of minutes. I believe much of this time is spent deploying & updating these resources, one set per branch:

1. S3 bucket
2. CF distribution
3. Lambdas (ISR, image, SSR)
4. SQS queue
5. IAM roles

Spinning up each one of these resources takes time. Also, unfortunately, they are left behind when the branch is destroyed (#277, #2123, #2180).

While I understand that it would be complicated on your end, one of the required steps forward to solving solving build time problems is to use a single set of resources per application, rather than per branch.

Related: #2127.

### Expected behavior

Use a single stack of resources per application rather than per branch to improve Next.js SSR build times.

### Reproduction steps

N/A

**Comment by ferdingler** [comment]
Hi @quinnturner, thank you for bringing up suggestions and ideas to improve Amplify Hosting. We really appreciate it. 

Let me add some clarification here. You are correct that we create a new stack of resources for every  branch, however, we do not deploy to all branches on every build, we only deploy the branch that had changes. So combining all branches into the same stack of resources will not help improve our deployment times. 

The reason for deployment times taking several minutes (~6 to 13 minutes) is because of the propagation time of the CloudFront distribution across all edge locations globally. The deployment itself (updating the code and creating resources) is actually pretty fast, but the rest of the time is just waiting for propagation to finish. We are aware customers like faster deploy times and we are looking into ways to improve this. 

Thanks again

**Comment by ferdingler** [comment]
> Also, unfortunately, they are left behind when the branch is destroyed

Forgot to mention that we have fixed the bug in which resources were left behind for disconnected branches. It should not be happening anymore.

**Comment by RonakShah** [comment]
It's been a year... Any progress on this @ferdingler ?

Mostly it gets stuck at
```
[INFO]: info  - Collecting page data...
[INFO]: info  - Generating static pages (0/29)
```
