### ISSUE TITLE
How to retrieve associated CloudFront Distribution URL?

### ISSUE THREAD

**Issue by joecritch** [aws-amplify/amplify-console#2486]
Hello, is it possible to programatically retrieve the URL of an Amplify's app CloudFront Distribution?

If I was to create a new **Next.js** app within the Console, there is an important 200 rewrite that gets added in 'Redirects & Rewrites', which points all front-end paths to the associated CloudFront Distribution. However, I'm now migrated to using Terraform's aws_amplify_app, which doesn't add this rewrite automatically.

So, I was wondering if anyone could help me figure out a way to do this (with an Amplify API, or with the TF provider)?  (Aside from looking up the URL in AWS Console and manually adding to my TF file)

Alternatively, if it is not exposed, is there a way for Amplify to still handle this internally when using Terraform?

```tf
resource "aws_amplify_app" "ui" {
  name       = "my-ui"
  ...

  custom_rule {
    source = "/<*>"
    status = "200"
     ## TODO -- this should be softcoded as the URL of the newly created CloudFront distribution
    target = "https://xxxxxxxxx.cloudfront.net/<*>"
  }
}
```

**Comment by ferdingler** [comment]
Hi, we don't have a way to retrieve this programmatically in any of our APIs unfortunately. But we add this redirect rule automatically for you during the Deployment phase, which is when the CloudFront distribution is created in your account. You shouldn't need to add it manually. 

If this rule is not being created for you, it's likely because your app is not recognized as SSR. Make sure that your app has an associated IAM role with SSR permissions when you create the app via Terrraform. 

Here is our troubleshooting guide too: https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#troubleshooting-ssr-deployment. 

Feel free to re-open if you have more questions.

**Comment by joecritch** [comment]
@ferdingler Thank you for the response!
