### ISSUE TITLE
DomainKeys Identified Mail still pending

### ISSUE THREAD

**Issue by umerghori786** [aws-amplify/amplify-console#2511]
Hi my region US East (N. Virginia) us-east-1... I made an identity of domain with this name mail.escuela-ray-bolivar-sosa.com..but my status is still pending how i change it to the "approved"
![image](https://user-images.githubusercontent.com/65702036/149512570-7dc30ba5-5ec0-407b-8333-667ca1ce2917.png)

i read documentation but i didnot understand it. kindly help
Thanks

**Comment by hloriana** [comment]
Hi @umerghori786 👋🏽 , thanks for reaching out. Please review this troubleshooting guide for DKIM issues: https://docs.aws.amazon.com/ses/latest/dg/troubleshoot-dkim.html. If you need further assistance please [create a Support Case](https://docs.aws.amazon.com/awssupport/latest/user/case-management.html#creating-a-support-case) so that you can receive better assistance since this GitHub repository is for addressing questions regarding the AWS Amplify Console.
