### ISSUE TITLE
SSL certificate for subdomain only.

### ISSUE THREAD

**Issue by chrisdelambert** [aws-amplify/amplify-console#2517]
**Please describe which feature you have a question about?**
We have an Angular app hosted on Amplify. I'll use example domains to explain my problem.

Under domain management in the Amplify console I have added custom domain "ambulance.com", and added "sub.ambulance.com" as a subdomain, the subdomain points to the environment the app is hosted on. "ambulance.com" is hosted with another provider. So to be clear, only sub.ambulance.com points to AWS servers.

Once domain ownership is verified, AWS creates a certificate for "ambulance.com" and "*.ambulance.com"

The problem is, We only want the certificate to cover "sub.ambulance.com". Not any wildcards or the root domain.
Is it possible to do this in Amplify? Could I create a certificate in Amazon Certificate Manager and somehow add it to this Amplify app?

**Comment by ferdingler** [comment]
Hi @chrisdelambert, we always provision a certificate that covers all subdomains within the provided root domain. This is so that if you deploy new subdomains to Amplify for new branches, we can reuse the same certificate. 

What I recommend is for you to associate `sub.ambulance.com` as the root domain so that the certificate we provision ends up being `*.sub.ambulance.com`. If you are hosting this domain on Route53, you simply need to add a new hosted zone for `sub.ambulance.com` so that it becomes a root domain. 

Feel free to re-open if you have further questions!
