### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by MathewGrg** [aws-amplify/amplify-console#273]
**App Id**: d354bd4zg4nrtl
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Deleted DNS hosting and transferred my domain from GoDaddy to AWS. But the domain is still connected to GoDaddy. Got hold of GoDaddy customer service people and apparently got this fixed, but still can't add the domain to an Amplify App. The domain still is loading old pages from GoDaddy hosting services. Contacted GoDaddy people again, only to be told, Amazon needs to update the CNAME from their end

**Error message**
> "One or more of the CNAMEs you provided are already associated with a different resource." 

![CNAME Error Message](https://user-images.githubusercontent.com/47274988/69674363-58c36680-106a-11ea-92a7-662134af05b5.jpg)

**Comment by kahdojay** [comment]
Hi @MathewGrg, this may be due to the DNS record already pointing to an existing distribution. A CNAME alias (domain) can only be used with a single CloudFront distribution at a time. These guides are helpful for getting started with custom domains:

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

Please let us know if you have any questions!
