### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by bpatrick3412** [aws-amplify/amplify-console#286]
**App Id**: d3afrj90bx42ho
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
When we click to "retry" button in domain configuration we have a error in console and domain configuration don't start.
**Error message**
Domain activation error: One or more of the CNAMEs you provided are already associated with a different resource.
Console "Retry" button error: backend.js:30 Uncaught TypeError: Cannot read property 'isFailed' of undefined
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Console error screenshot: https://prnt.sc/q5j97c .

**Comment by kahdojay** [comment]
Hi @bpatrick3412, this may be due to the DNS record already pointing to an existing distribution. A CNAME alias (domain) can only be used with a single CloudFront distribution at a time. These guides are helpful for getting started with custom domains:

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

Please let us know if you have any questions!
