### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by hjkimu** [aws-amplify/amplify-console#289]
**App Id**: d2mxpx44rwpn08
**Region**: ap-northeast-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by kahdojay** [comment]
Hi @hjkimu, this may be due to the DNS record already pointing to an existing distribution. A CNAME alias (domain) can only be used with a single CloudFront distribution at a time. These guides are helpful for getting started with custom domains:

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

Please let us know if you have any questions!
