### ISSUE TITLE
Build Failed: Vue JS with Gridsome framework

### ISSUE THREAD

**Issue by jmodanwal** [aws-amplify/amplify-console#297]
**Describe the bug**
I am trying to connect my vue app hosted on bitbucket master branch. When I try to connect app then build failed after some times.

Can you please help me out ?

Thanks

**Comment by swaminator** [comment]
What's the build error you're getting?

**Comment by jmodanwal** [comment]
> What's the build error you're getting?

Hi
I am attaching here  error log. Please check

Thanks
[log.txt](https://github.com/aws-amplify/amplify-console/files/3951528/log.txt)

**Comment by kahdojay** [comment]
@jmodanwal please copy and paste the relevant errors as a comment. 

Can you also please fill in the issue template:
1. Issue Description

2. Detailed Steps To Reproduce

3. Expected behavior

4. Application Details

    a. Please share your Amplify Console AppID, found in App settings > General > App ARN (e.g. arn:aws:amplify:us-west-2:XXXXXXXXXXX:apps/APPID)

    If the issue is related to a build, please also share:

    b. The specific Build number(s) we should investigate

    c. Your buildspec (the version at the time the issue occurred), either from the Amplify console or amplify.yml (Be sure to remove any sensitive data)

5. Sample code Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)
