### ISSUE TITLE
Domain activation is Failed

### ISSUE THREAD

**Issue by refundr** [aws-amplify/amplify-console#346]
**App Id**: d2ja55o4b4vfgo
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

**Issue/question**

**Comment by donkahn** [comment]
Hi @refundr, this may be due to the DNS record already pointing to an existing distribution. A CNAME alias (domain) can only be used with a single CloudFront distribution at a time. These guides are helpful for getting started with custom domains:

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

Please let us know if you have any questions!

**Comment by kahdojay** [comment]
Hi @refundr, this may be due to the DNS record already pointing to an existing distribution. A CNAME alias (domain) can only be used with a single CloudFront distribution at a time. These guides are helpful for getting started with custom domains:

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

Please let us know if you have any questions!

**Comment by kahdojay** [comment]
Closing this one for now, please feel free to re-open if you're still blocked
