### ISSUE TITLE
Amplify Console build fails (API/RDS). Is team-provider-info.json ignored?

### ISSUE THREAD

**Issue by danieletieghi** [aws-amplify/amplify-console#350]
I have a simple (for now) Amplify Project with a GraphQL API with an RDS (Aurora Serverless) datasource.
Everything is working fine with "amplify push" but the build from the console (same environment) fails because it hangs with an input like if the datasource in the environment was never initialized (? Provide the region in which...):

![AWS_Amplify_Console](https://user-images.githubusercontent.com/2631884/71689569-a6866980-2da2-11ea-9976-1af2f665ef67.jpg)

While this parameters are already defined in the team-provider-info.json file.

![team-provider-info_json_—_ethicar](https://user-images.githubusercontent.com/2631884/71689716-0ed54b00-2da3-11ea-9d12-4308d506963a.jpg)

**Comment by danieletieghi** [comment]
Does anybody have the same problem (or nobody using RDS nowadays...)?
Any workaround for this?
Thankyou!

**Comment by danieletieghi** [comment]
Anything I can do to help solve this problem?

**Comment by swaminator** [comment]
@danieletieghi we have been looking into it and have a fix on the way!

**Comment by danieletieghi** [comment]
Thank you very much! And thank you @UnleashedMind!

**Comment by danieletieghi** [comment]
With @aws-amplify/cli@4.13.0 now works! Thank you everybody!

**Comment by jcvalerio** [comment]
@swaminator  this issue still present on latest version like `4.32.1`

We use the *PR Preview* feature, so we have to create the environment at runtime, so add those values on the `amplify/team-provider-info.json` is not an option

we have a custom `amplifyPush` to do the headless workflow but this didn't work because, the amplify console have no idea of how handle the `RDS` settings


At the Amplify Console the build got stuck, but nothing was shown 

<img width="1390" alt="image" src="https://user-images.githubusercontent.com/2169894/108138211-15944f80-7083-11eb-8f88-373deb808824.png">


Running the script locally with the same env variables

<img width="950" alt="image" src="https://user-images.githubusercontent.com/2169894/108138445-9c492c80-7083-11eb-9bc7-4546d7e81dd0.png">

We can see the console got stuck waiting for user confirmations

Related with [Headless push with Aurora doesn't work #5536](https://github.com/aws-amplify/amplify-cli/issues/5536)
