### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by NinaKWelch** [aws-amplify/amplify-console#381]
**App Id**: d20laet6xu0noq
**Region**: eu-west-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I am unable to connect my domain with AWS Amplify where my static web pages are located.

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
I would like to have the domain connected with Amplify instead of S3.

**Comment by Joycehao19** [comment]
Hi @NinaKWelch , the reason is a CNAME alias (domain) can only be used with a single CloudFront distribution at a time. These guides are helpful for getting started with custom domains:
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

Please let us know if you have questions!

**Comment by NinaKWelch** [comment]
Thank you.

I managed to sort it out as instructed.

Nina

**Comment by kahdojay** [comment]
Thanks for letting us know - feel free to let the us and the community know what the specific blocker was in case they experience the same. Closing this for now.
