### ISSUE TITLE
Build successfull but is marked as failed

### ISSUE THREAD

**Issue by MaximilianFranke** [aws-amplify/amplify-console#409]
Hey guys,
my problem is that the deploy process not start, cause the frontent build seems to be failed. But the build should successfull, how you can see in the log:

```
2020-02-05T09:33:21.194Z [INFO]: DONE  Build complete. The dist directory is ready to be deployed.
2020-02-05T09:33:21.194Z [INFO]: INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
                                 
2020-02-05T09:33:21.772Z [INFO]: # Completed phase: build
2020-02-05T09:33:21.774Z [INFO]: ## Build completed successfully
```

Here are my build settings:
```
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build:$USER_BRANCH
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
  
```

**Comment by swaminator** [comment]
Can you please share your AppID? It's found in AppSettings > General under AppARN

**Comment by MaximilianFranke** [comment]
App ARN arn:aws:amplify:eu-central-1:064480943479:apps/d3s4jihdbyzh2

**Comment by Joycehao19** [comment]
Hi @MaximilianFranke , can you provide the build number as well? Thanks

**Comment by MaximilianFranke** [comment]
Since a view days its works again with out any Problems.
Some affected build samples:
Dev Build#364 - Build#372

**Comment by Joycehao19** [comment]
Hi @MaximilianFranke , your build are failing on "dev" branch due to a known issue related to the maximum size of the cache artifact that's possible for a given branch. This bug currently limits the maximum size of that artifact to 1GB, which you has exceeded for the "dev" branch with the failing builds (the builds are eventually timing out and causing the failures).

You can work around this by creating a new branch within your app and connecting it to the Console (which gets a new cache artifact), or by disabling build caching in your build spec; under "frontend: > cache: > paths:" remove all child entries from "paths:" so that it simply reads:
```
cache:
  paths:
```
We are tracking this issue in our product backlog for an eventual fix to the 1GB size limitation.

**Comment by MaximilianFranke** [comment]
ok thank you, if its happens again. i will try it!
