### ISSUE TITLE
Amplify console build successful but fails to move to deploy

### ISSUE THREAD

**Issue by bakeruk** [aws-amplify/amplify-console#41]
Hi,

I am using Amplify to build my companies new website using **Gatsby** and it has been a huge success until Thursday (16th May 2019).

The build logs say that our app has built successfully however, the Amplify console status is saying that they build has failed. After Googling the issue I found this solution on Github aws-amplify/amplify-cli#1415.

It states that the cache was too large - so I removed the cache rules in the build settings Yaml file (in code and in the console) but still no luck. Without any additional logging, I cannot pinpoint the issue other than it could possibly be within Amplify itself.

**Note: I get a green notification bar at the top say that the build was successful.**

```
2019-05-20T11:58:42.054Z [INFO]: success run page queries — 126.669 s — 200/200 1.58 queries/second
2019-05-20T11:58:42.067Z [INFO]: success write out page data — 0.007 s
2019-05-20T11:58:42.069Z [INFO]: success write out redirect data — 0.001 s
2019-05-20T12:04:20.109Z [INFO]: 
2019-05-20T12:04:20.308Z [INFO]: success Build manifest and related icons — 0.097 s
2019-05-20T12:04:20.309Z [INFO]: success onPostBootstrap — 0.099 s
                                 info bootstrap finished - 494.906 s
2019-05-20T12:05:12.082Z [INFO]: success Building production JavaScript and CSS bundles — 51.745 s
2019-05-20T12:05:23.194Z [INFO]: success Building static HTML for pages — 11.111 s — 200/200 117.51 pages/second
2019-05-20T12:05:23.241Z [INFO]: info Done building in 557.838 sec
2019-05-20T12:05:23.517Z [INFO]: Done in 572.20s.
2019-05-20T12:05:23.522Z [INFO]: # Completed phase: build
                                 # Starting phase: postBuild
2019-05-20T12:05:23.525Z [INFO]: # Executing command: du -sh ./public/
2019-05-20T12:05:23.556Z [INFO]: 995M	./public/
2019-05-20T12:05:23.557Z [INFO]: # Executing command: du -sh ./node_modules/
2019-05-20T12:05:23.669Z [INFO]: 518M	./node_modules/
2019-05-20T12:05:23.669Z [INFO]: # Completed phase: postBuild
2019-05-20T12:05:23.670Z [INFO]: ## Build completed successfully
2019-05-20T12:05:23.671Z [INFO]: # Starting caching...
2019-05-20T12:05:23.761Z [INFO]: Creating cache artifact...
2019-05-20T12:06:08.305Z [INFO]: Uploading cache artifact...
2019-05-20T12:06:14.769Z [INFO]: # Caching completed
```

The ARN is: `arn:aws:amplify:eu-west-1:193471113837:apps/d30v7a1bgav5mq`

Any ideas?

**Comment by swaminator** [comment]
@filipemcg we are now on GitHub issues. Please share your appid (found in App Settings > General)

**Comment by garyleefight** [comment]
@filipemcg Hi, I searched your build logs. Seems like the job 8 you had run should failed at build stage, but due to our console bug it didn't. The error message in logs: [ERROR]: !!! Error: Artifact directory doesn't exist: public. This is because your build directory public doesn't exist after build. 
You may have to reset the build directory in build settings. We will work on fix the missing catching error bug.

**Comment by swaminator** [comment]
@filipemcg were you able to fix the issue?

**Comment by christina-immanuel** [comment]
Hi, I'm facing the same issue. The build passes in the CLI but the web deploy fails with the error as above.

**Comment by bakeruk** [comment]
Amplify has a maximum deploy size of 1GB.

The devs are going to remove this in the future but for now, they will have to manually up the size on your account themselves.

I would create a new issue and wait for a response for this to happen or spam your comments here to speed things up ;)

**Comment by bordeo** [comment]
@swaminator 
I have the same problem with my app d1ll0ojvkzv9e7

Could you help me?

**Comment by rnaresh** [comment]
@swaminator 
I have the same problem. After removing the preview branches, redeployment was successful
What could be the reason?
App ARN - arn:aws:amplify:us-east-2:582734241681:apps/dpwfbpxczhwpr

**Comment by bakeruk** [comment]
> Amplify has a maximum deploy size of 1GB.

Hope that helps.

**Comment by rnaresh** [comment]
Thanks @bakeruk 
In our case, the artifact size is 45MB and i have 4 deployments at max when the deployment failed

**Comment by Joycehao19** [comment]
Hi @bordeo , which region did you use?

**Comment by bordeo** [comment]
We removed the amplify app because we need to move forward with the project. So we deployed by our own on an S3 bucket + cloudfront

>

**Comment by Ben-Kincaid** [comment]
Just wanted to share what was causing this for me and my solution:

Our build previews were hanging on our production server - after build, it simply wouldn't continue to deploy and would timeout. The error logs gave no additional info on what the issue was or why the build wasn't able to proceed past the "build" step.

The amplify.yml for the project defined a test phase, even though our E2E tests aren't ran during production build, only for our development build. 

In the amplify console in our production projects "build settings", we did not have a test phase specified, but since our projects 'amplify.yml' DID specify this phase, it seems that amplify got confused and would simply time out when getting to where the "test" step would be ran. Manually adding `USER_DISABLE_TESTS` to true in our environment variables allowed for amplify to clarify whether or not to run the test phase and our redeploy of our preview was successful.

So, if you anyone is having this issue, verify that your `amplify.yml` isn't specifying a test phase unless your build settings also specify this. If you need to specify a test phase in your `amplify.yml`, make sure any environments either also have this test phase in their build settings OR set `USER_DISABLE_TESTS` env variable to true if you don't need to run tests in that environment.

Would be great if amplify allowed our .yml file to be our "single source of truth" to avoid parity issues between our build settings specified in "build settings" and `amplify.yml`. For example, It also seems silly that i have to add a "test" phase in build settings to see the test step at all during build, even if my amplify.yml has that phase specified.

**Comment by afladmark** [comment]
Since you were previously directing people to email, I contacted you on December 10th there. On the 18th you replied asked me to post here, so I'm doing so, but I really would appreciate a timely response with a resolution or some guidance please.

I manage a relatively large Gatsby site on AWS Amplify Console. We recently added a fairly large amount of image content (a couple thousand images, for which Gatsby creates multiple responsive size and format variants of each). Our builds now won't succeed. It says the build finished, but it didn't. And the deploy just fails with no useful log output.

After finding this and other issues here on Github, it would appear there's a 1GB limit which may be what's preventing these builds from completing and deploying? (The relevant failing builds were for the staging branch on the 9th of December. I've since rolled it back.)

Our appArn is arn:aws:amplify:us-west-2:134171893859:apps/d3o2hnjl44rlyj

Is it possible to have this limit extended to allow us to have perhaps 3-4 gb per deployment? While it is quite a lot, virtually all of it will be generated one time and then cached unmodified for future deployments. So ideally, it'll run once taking a couple hours and generating the images. Future builds will then use the cache of that public folder and thus will skip regenerating the images again.

I'd like to understand if you can flex this limit for us (as you seem to have done for others) ASAP so we can keep using Amplify. There's so many great features and it's evolving very quickly, so we'd really rather not try to set this all up ourselves just because of this size limit. But on the other hand, having these images correctly sized and available in multiple formats (webp, png, etc) makes a huge difference, especially to mobile page load speed, so we'll almost certainly take that performance win over the hosting convenience.

Please let me know how we should proceed.

Thanks very much,
Andrew

**Comment by swaminator** [comment]
@afladmark are you seeing the following deploy error? 
```
2019-12-28T21:31:00 [INFO]: Starting Deployment
2019-12-28T21:31:00 [ERROR]: Failed to deploy
2019-12-28T21:31:00 [INFO]: Deployment finished.
```

**Comment by afladmark** [comment]
@swaminator Yes, the build step is marked with a green check suggesting it has completed (though the build log itself if incomplete. It is unclear if it's truncated or unfinished as It doesn't say anything, it just cuts off). But the deploy step started and just says:
```
2019-12-09T04:16:33 [INFO]: Starting Deployment
2019-12-09T04:16:33 [ERROR]: Failed to deploy
2019-12-09T04:16:33 [INFO]: Deployment finished.
```
That's from build 291 on the staging branch I referenced above.

**Comment by dasiarg** [comment]
@afladmark good afternoon

Im facing a similar issue while trying to deploy a React build by npm from Bitbucket's Amplify Console integration.

I just installed the pipeline.

2020-01-29T16:51:56.458Z [INFO]: # Completed phase: build
2020-01-29T16:51:56.460Z [INFO]: ## Build completed successfully
2020-01-29T16:51:56.561Z [INFO]: # Starting caching...
2020-01-29T16:51:56.628Z [INFO]: Creating cache artifact...
2020-01-29T16:52:03.117Z [INFO]: # Cache artifact is: 73MB
2020-01-29T16:52:03.209Z [INFO]: # Uploading cache artifact...
2020-01-29T16:52:04.216Z [INFO]: # Caching completed
2020-01-29T16:52:04.310Z [ERROR]: !!! Error: Artifact directory doesn't exist: /var/www/html/en
2020-01-29T16:52:04.310Z [INFO]: # Starting environment caching...
2020-01-29T16:52:04.311Z [INFO]: # Environment caching completed
Terminating logging...

**Comment by 8ctopotamus** [comment]
I am also running into this error with a Gatsby project. It makes it passed the BUILD stage and fails on DEPLOY. It randomly starts to work again after attempting about 3 deploys.

```
2020-03-29T14:11:40 [INFO]: Updating Edge config
2020-03-29T14:11:40 [ERROR]: Failed to deploy
2020-03-29T14:11:40 [INFO]: Deployment finished.
```

**Comment by swaminator** [comment]
@8ctopotamus @dasiarg @afladmark @bordeo @bakeruk @filipemcg @christina-immanuel we are tracking Deploy failures on this ticket #115. Closing this ticket to track it in a single place.
