### ISSUE TITLE
My site is no longer working - giftsgoodandbad.com

### ISSUE THREAD

**Issue by bolzon2000** [aws-amplify/amplify-console#461]
I've made no changes to my site and am now receiving the below error for giftsgoodandbad,.com

Firefox detected an issue and did not continue to giftsgoodandbad.com. The website is either misconfigured or your computer clock is set to the wrong time.

It’s likely the website’s certificate is expired, which prevents Firefox from connecting securely. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.

**Comment by Joycehao19** [comment]
@bolzon2000 It seems like you need to activate the SSL certificate of your custom domain.

**Comment by bolzon2000** [comment]
The SSL certificate was created by the Amplify Console and was working when I first built and deployed my app. 
I'm unclear as to how I should proceed.

**Comment by Joycehao19** [comment]
@bolzon2000 what is your appId and region?

**Comment by bolzon2000** [comment]
d10m7he09znso3  Oregon

**Comment by Joycehao19** [comment]
Hi @bolzon2000 , the certificate expired on 2019-12-20 12:00:00, which is the reason you are seeing the issue in Firefox. The certificate was not renewed because the renewal was pending validation. It seems like the certificate were removed between initial certificate request and the renewal. 

**What you can do:** remove your custom domain, double check the DNS record and re-add the your domain again. It would work again.

**Comment by swaminator** [comment]
@bolzon2000 can you check your DNS provider to see if the CNAME we use for cert validation still exists? It should look something like `_randomids.acm-validation.aws.`

**Comment by Athena96** [comment]
Closing this issue, please feel free to re-open if you are still facing issues.
