### ISSUE TITLE
CloudFormation Stack Update "Blast Radius"

### ISSUE THREAD

**Issue by alexkates** [aws-amplify/amplify-console#505]
** Please describe which feature you have a question about? **
Irrespective of the type of Amplify Category change, it seems that amplifyPush is triggering a CloudFormation stack update for every stack. Is this intended? Are there any fine grained controls I can use to only trigger updates to changed templates?

** Provide additional details**
For example, If I were to simply change code in a REST API's lambda function and commit, looking at the backend build logs, it appears that every stack that is part of my app is triggering an update. Ideally, only the affected stacks would trigger updates.

**Comment by cslogan-red** [comment]
The answer here is a little more complicated than it appears. **TLDR;** _CloudFormation is not actually modifying your nested stack's unless the templates have actually changed since the last deployment, however you may still see "updating" messages while it validates._

When the Amplify CLI does an "amplify push", either via a build locally or in the Amplify Console build container, there are a number of reasons why a nested CloudFormation stack (like auth or a lambda function, etc) appears to be updating, however the resource is only ever actually _modified_ if there's a difference in the CF template since the last deployment.

That said, _**every time**_ a backend deployment updates the root CF stack (like when modifying another or adding a new nested resource), each nested stack is validated as to whether or not it needs to be modified. In the Amplify Console build logs, this can make it seems like nested child stacks are being updated even when you've made no changes to them, like in the case below, for an auth and lambda function:

<img width="836" alt="build_log" src="https://user-images.githubusercontent.com/1307688/76471954-597dcf80-63b1-11ea-8e7a-f740ce912213.png">

You can likewise see this behavior in the corresponding backend environment's CF event log in Amplify Console:

<img width="1261" alt="cf_root_log" src="https://user-images.githubusercontent.com/1307688/76471995-787c6180-63b1-11ea-9f7b-68cb4c2f3ed0.png">

However, in this case, an update was triggered on the root stack and the update messages you see in each nested stack is just CF _checking_ whether or not the resource actually needs to be modified, if it hasn't changed since the last deployment, it won't be modified.

You can validate this by clicking the "View in CloudFormation" button in the upper right, and then looking at the actual nested child stacks that Amplify creates for your individual resources and see that the last updated time hasn't changed since the last time it was actually modified, and there are no modification events for that nested stack during the root stack update timeframe. As an example, the auth resource above that shows the update message was never _actually_ modified because it did not change since the last deployment.

<img width="265" alt="cf_child_stack" src="https://user-images.githubusercontent.com/1307688/76472086-cb561900-63b1-11ea-983f-68ea82c624d4.png">

**Comment by alexkates** [comment]
Thank you @cslogan-red for the detailed  and helpful response! This makes sense, and now that I look it's also the behavior I am seeing.
