### ISSUE TITLE
Domain activation is Failed - How to find all CNAME associated ARN resources

### ISSUE THREAD

**Issue by levu48** [aws-amplify/amplify-console#534]
**App Id**: d2tprwijv7y6b8
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: 

I need to set up a website for a domain.

**Issue/question**

I have tried to check all of the arn resources, cloud distribution, etc. and gone through the process many times, but could not get it to work. So the question is what is the definitive way to find out what ARN resources are associated with a CNAME in AWS?

**Error message**

Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by Athena96** [comment]
@levu48 so to confirm, you have verified that your domain is not already used in a CloudFront distribution?

**Comment by levu48** [comment]
That is correct. I have checked it many times and deleted all related to
the domain name on CloudFront.

**Comment by Athena96** [comment]
@levu48 it looks like you currently have a custom domain associated with your Amplify app (which was registered around 01/09/2020), is that right? And You're trying to switch to a new domain now?

**Comment by levu48** [comment]
I tried to have another domain added to it.

**Comment by Athena96** [comment]
So, you're trying to associate 2 different URLs with the same app. The first 1 succeeded, but when you are trying to add the 2nd custom domain, it fails with this error you described. Is that correct?

**Comment by levu48** [comment]
That is correct. Actually I tried the failed one first, but it failed. So I
tried another one just to test, ant that worked. I went back to check on
the original one and tried to clear all associated resources, but it never
worked.

**Comment by adriencg** [comment]
@levu48 The two places to check are:
- Route53 RecordSet for your hosted zone
- CloudFront distributions

Since you said you deleted/removed all associated CF resources, I'd look at R53. It's likely that you have a CNAME pointing to a CF distribution there as well as an A record ALIAS to CF. Please make sure you remove all of those as well. 

If your domain isn't registered with Route53, you'll need to check w/ your provider about how to manage the dns records. https://docs.aws.amazon.com/amplify/latest/userguide/howto-third-party-domains.html has more info if it's relevant to you.

**Comment by Joycehao19** [comment]
Closing for now. If you still face same issues, please feel free to reopen it!
