### ISSUE TITLE
https.domain.co.uk - "Attackers might be trying to steal your information"

### ISSUE THREAD

**Issue by Zurdge** [aws-amplify/amplify-console#597]
App Id : arn:aws:amplify:us-east-1:001683458534:apps/d2senbpo6qq3x7
Region : us-east-1
Step : setting up custom domain
Status : working but not perfect

Hi,
I have a custom domain setup after following these steps
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html
https://docs.aws.amazon.com/amplify/latest/userguide/howto-third-party-domains.html

1 - http://domain.co.uk -> routes to https://www.domain.co.uk ( Works )
2 - https://domain.co.uk -> routes to https://www.domain.co.uk ( Fails )
2 - "Your connection is not private, Attackers might be trying to steal your information"

The error in example 2 is something I'd like to fix as it looks bad for customers.

Thanks,

**Comment by adriencg** [comment]
I believe you're facing this issue: https://www.godaddy.com/community/Managing-Domains/Root-Domain-Forwarding-with-SSL-and-without-IP/td-p/156935 I was able to repro w/ my GoDaddy domain and couldn't find an easy workaround.

I'd suggest https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-transfer-to-route-53.html if you're going to be hosting with Amplify, which definitely supports both root and www.root domains. You can also try the referred-to 'Cloudflare' solution in the godaddy link above. 

Closing for now since as this is a Godaddy-specific issue.
