### ISSUE TITLE
Incoming webhook don't add to amplify app with CloudFormation

### ISSUE THREAD

**Issue by hiennguyen-agilityio** [aws-amplify/amplify-console#633]
** Please describe which feature you have a question about? **
I have issue with Incoming webhook when create amplify via CloudFormation template. The incoming webhook added to github but don't appear on Amplify app

** Provide additional details**
Cloudformation template
```
---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ServiceName:
    Description: The personal access token
    Type: String
    Default: earlybird
  Environment:
    Description: The environment
    Type: String
    Default: dev
  Repository:
    Description: The repository for an Amplify App
    Type: String
    NoEcho: true
    AllowedPattern: ".+"
  GitToken:
    Description: The personal access token
    Type: String
    NoEcho: true
    AllowedPattern: ".+"
  Branch:
    Description: The branch name, which use to build admin dashboard app
    Type: String
    AllowedPattern: ".+"
  CognitoPoolID:
    Description: The cognito user pool ID
    Type: String
  CognitoRegion:
    Description: The cognito user pool region
    Type: String
  CognitoClientID:
    Description: The cognito user client ID
    Type: String
  AuthenticationFlow:
    Description: The cognito user client key
    Type: String
    Default: USER_SRP_AUTH
  AppSyncEndpoint:
    Description: The cognito user pool ID
    Type: String
  AppSyncRegion:
    Description: The cognito user pool region
    Type: String
  AppSyncAuthType:
    Description: The cognito user client key
    Type: String
    Default: AMAZON_COGNITO_USER_POOLS
  SSMParamVersion:
    Description: The SSM Parameter version
    Type: Number
    Default: 1

Resources:
  GitTokenParameters:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${ServiceName}/${Environment}/GITHUB_OAUTH_TOKEN"
      Type: String
      Value: !Ref GitToken

  AdminAmplify:
    Type: AWS::Amplify::App
    DependsOn: GitTokenParameters
    Properties:
      Name: AdminWebServer
      Repository: !Ref Repository
      AccessToken: !Join
        - ''
        - - '{{resolve:ssm:'
          - !Ref GitTokenParameters
          - ':'
          - !Ref SSMParamVersion
          - '}}'
      EnvironmentVariables:
        - Name: REACT_APP_AWS_COGNITO_REGION
          Value: !Ref CognitoRegion
        - Name: REACT_APP_AWS_USER_POOL_ID
          Value: !Ref CognitoPoolID
        - Name: REACT_APP_AWS_USER_POOL_WEB_CLIENT_ID
          Value: !Ref CognitoClientID
        - Name: REACT_APP_APPSYNC_GRAPHQL_ENDPOINT
          Value: !Ref AppSyncEndpoint
        - Name: REACT_APP_AWS_APPSYNC_REGION
          Value: !Ref CognitoRegion
        - Name: REACT_APP_AWS_APPSYNC_AUTHENTICATION_TYPE
          Value: !Ref AppSyncAuthType
        - Name: REACT_APP_AWS_AUTHENTICATION_FLOW_TYPE
          Value: !Ref AuthenticationFlow
      BuildSpec: |
        version: 0.1
        frontend:
          phases:
            preBuild:
              commands:
                - npm install
            build:
              commands:
                - yarn build
          artifacts:
            baseDirectory: build
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*

  AdminDeployBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AdminAmplify.AppId
      BranchName: !Ref Branch
```
The webhook added to github

![Screen Shot 2020-04-29 at 11 34 27](https://user-images.githubusercontent.com/5277254/80561091-83e12600-8a0d-11ea-948f-a7ef6f627b80.png)
But the incoming webhook in app is empty

![Screen Shot 2020-04-29 at 11 34 43](https://user-images.githubusercontent.com/5277254/80561094-88a5da00-8a0d-11ea-894b-d4b1d51c8533.png)

I make the auto-build does not trigger when the code has been pushed to github

I don't found any way to add incoming webhook to the CloudFormation template in the document(https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amplify-app.html). How to add incoming webhook to CloudFormation template?

**Comment by kahdojay** [comment]
@hiennguyen-agilityio ["Incoming" webhooks is a separate feature](https://docs.aws.amazon.com/amplify/latest/userguide/webhooks.html) not related to automatically triggering builds upon a `git push` so you wouldn't see anything there (and indeed creating incoming webhooks is not currently supported within our integration with CloudFront)

It looks like you don't have [`EnableAutoBuild: true`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amplify-branch.html#cfn-amplify-branch-enableautobuild) on your branch resource, you'll need that for branch builds to be auto-triggered by github webhook triggers.

Also that webhook doesn't look correct since it doesn't have your appId being passed in as a query param, did you create it manually? As long as you provide a valid GitHub OAuth token and the webhook doesn't already exist for the appId, Amplify creates it for you.

If that doesn't work for you also check that your value for repository does not include the ".git" and is just `https://github.com/username/reponame`, and if you're still having issues please re-open this issue.
