### ISSUE TITLE
CloudFront Url not resolving but amplifyapp.com one is

### ISSUE THREAD

**Issue by kneekey23** [aws-amplify/amplify-console#78]
**Describe the bug**
The cloudfront url for my custom domain is using does not resolve: 
d1i8yb92ntu6lx.cloudfront.net

but the amplifyapp one does:
https://master.d25d79wvu5bahq.amplifyapp.com

**To Reproduce**
I checked in some new code and the build process kicked off and then this happened. I am not sure why when the build succeeded.

**Expected behavior**
I expected the cloudfront distribution cache to be invalidated and for it to start working with the new code. Since i cant access the underlying distribution I can't debug this or figure out why cloudfront doesn't like the updates.

**Comment by kneekey23** [comment]
@nimacks 
1. I am able to view it with the default amplifyapp domain but not the custom domain after an update.
2. custom domain is configured like so in amplify console
<img width="1311" alt="Screen Shot 2019-08-28 at 9 09 34 PM" src="https://user-images.githubusercontent.com/8533749/63909619-29a04900-c9d8-11e9-8ef8-1e03aacfc699.png">
then i have forwarding set up in my dns settings in my godaddy account as well as the appropriate CNAME records according to the docs. I'm wondering if it's because it's a godaddy domain and I should move it to route53.

**Comment by nimacks** [comment]
@kneekey23 , this is great info. We can rule out any issues with our hosting infrastructure and focus on how your custom domain is set up. The forwarding option in GoDaddy at times is unreliable and thus our recommended solution would be to migrate your domain to Route53. 

Here are some steps: 

- Create a hosted zone for your domain (or transfer it if that's an option) in the AWS console. 
- Remove and re-add your custom domain in the Amplify Console.The Amplify Console would manage the creation of CNAME records for you making it super easy.

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html

let me know if this works for you.

**Comment by kneekey23** [comment]
@nimacks migrated and re-added in the amplify console! takes some time before the DNS servers will fully propagate all traffic since i changed the nameservers so i'll keep you posted but this is probably a much better solution, thank you so much for your help. And everything worked perfectly when i re-added the custom domain in amplify console so that was nice :)

**Comment by nimacks** [comment]
That's great to hear. Feel free to resolve this ticket, if you're satisfied that everything is working as expected.

**Comment by kneekey23** [comment]
Thanks!

**Comment by Ettery** [comment]
I'm also having this problem: the Amplify URL for my site is resolving:
    https://master.d357uat5p3cl17.amplifyapp.com/
but the Cloudfront URL I have been given to point my custom domain CNAME at is not, it returns an HTTP 404:
    https://d3dc3kbh8sa4rg.cloudfront.net/

![image](https://user-images.githubusercontent.com/4337479/148501905-ac4861b9-f960-4e23-aa7d-b7fca044787a.png)

Note that the CNAME is in place, it just hasn't propagated yet.

![image](https://user-images.githubusercontent.com/4337479/148501982-4308a999-eb4b-4bcc-9d33-3ac7e57c321e.png)

This is my second attempt to setup a custom domain (custom external domain is a showstopper for using Amplify) - I did the same with the Wild Rides sample, and experienced the same problem, so started a new site.  With my Wild Rydes attempt I waited until the CNAME propagated and the Domain Activation stage showed an error because it couldn't reach the site: both the custom domain and the Cloudfront URL returned 404s.
