### ISSUE TITLE
GitHub Webhooks

### ISSUE THREAD

**Issue by lukehedger** [aws-amplify/amplify-console#840]
Is it possible to see the webhooks that Amplify Console has registered with the connected GitHub repository?

Looking at the webhooks settings on a GitHub repository I have connected to Amplify Console, I can see an identical webhook has been registered **10 times**. The webhook URL is something like  https://xxxxxxxxxx.execute-api.eu-west-2.amazonaws.com/prod/github

GitHub imposes a limit of 20 webhooks registered to a single repository. I have other services that need to register webhooks, so I am now finding I regularly hit this limit.

If I could somehow see which Amplify webhooks are active, I could perhaps prune the registered webhooks. But it would also be useful to understand why/when Amplify registers a new webhook. I guess it is also possible that these are duplicate webhooks and there could be a bug somewhere.

```
appId: d9slrnc36kbq7
region: eu-west-2
```

**Comment by Athena96** [comment]
Hi @lukehedger you can view the webhooks for your app by opening the Repo in GitHub, then going to  Settings / Webhooks.

Multiple webhooks for with the same URL is due to deleting then re-adding the application. To clean up your webhooks, you can click on the webhook url, then scroll to the bottom of the page and find the date. Then keep the one with the latest date and delete the others. Thanks!

**Comment by lukehedger** [comment]
Thanks @Athena96
