### ISSUE TITLE
Is there a limit to number of redirect rules I can add?

### ISSUE THREAD

**Issue by drake-smith** [aws-amplify/amplify-console#851]
** Please describe which feature you have a question about? **
Hi, I am scoping a project using AWS Amplify Console and I will have about 200 old legacy URL redirects from an existing site to preserve on the new website. 

When hosting static sites on S3 + CloudFront, the S3 redirect rules field limits the XML redirection rules you can add to 50. Is there a limit on Amplify Console on how many I can add? Thank you.

** Provide additional details**

**Comment by abhi7cr** [comment]
Hi @drake-smith,

We don't have an explicit limit enforced, but are aware of and working on fixing a known issue that results in an upper bound depending on the total number of files across all branches, the number of rewrite rules, etc.

**Comment by drake-smith** [comment]
@abhi7cr Thanks for your answer. Do you know generally from reports the number of rewrite rules before any issues might begin to occur?

**Comment by abhi7cr** [comment]
@drake-smith,
The upper limit in most cases is reached due the number of branches * total number of files per branch. It can reach the limit sooner if you have a very large number of redirects. One of the customers experienced this issue when they had around 15k redirects. But like I said, it depends on a combination of the number of files, number of branches, number of redirects, and few other properties.

**Comment by hsspain** [comment]
Closing this ticket.  If there are further questions, please let us know.

**Comment by autronix** [comment]
This still seems to be an issue. We've reached the limit at around 4090 rules, loaded through the CLI.

The error that the CLI throws is `You've reached the maximum configuration storage limit for this app, either remove some branches or reduce the number of redirects, rewrites or custom headers associated with this app.` - We've removed build branches and cleaned up a large number of files/configs only for a very marginal gain in rule count.

We've spent a significant amount of time developing around amplify as our SPA replacement for our existing wp site, lots of history, lots of redirects to keep our SEO ratings. 

At this time we have around 10k redirect rules we want to put in place in order to replace our existing site with our rebuild going off Amplify.

Is there:
1. A way to request of the "maximum configuration storage limit" from the amplify/aws team? 
2. A workaround to process the incoming request through lambda, .htaccess or something similar that would allow overcoming the limitation we're seeing with the number of active rules?

From the standpoint of our application, without a solution we need to move away from amplify and we're looking into netlify as a replacement, as it supports a file-based redirect rule-set.
We simply can't use amplify to release the application at this point into a production environment due to this, since our SEO would take a major hit without being able to keep those redirects.
