### ISSUE TITLE
GitHub Integration - I can't find the repo of a repo I am an "Outside Collaborator" on 

### ISSUE THREAD

**Issue by drake-smith** [aws-amplify/amplify-console#852]
**Please describe which feature you have a question about?** 
Connecting the GitHub repo to Amplify Console

 **Provide additional details**
I am building a client project. The GitHub repo is under their GitHub organization and I am added to that repo as an "Outside Collaborator" with Admin access (to the repo). I can't find the repo when I auth GitHub in Amplify Console and check the list of repos. What do I need to do in order for this repository to appear?

I would consider this a standard workflow for building a client site, where I may not be able to be added as a member of their GitHub organization, but instead am added just to the repository.

**Comment by abhi7cr** [comment]
Hello  @drake-smith, 

I was able to setup a test organization, and invite a test user I created as an outside collaborator. Then, I was able to use the test user's github to access the required repo under the org. You have to make sure to click request access next to the organization, when you first authorize Amplify to access the required organization, as follows:

![image](https://user-images.githubusercontent.com/5371802/87477498-104ac000-c5dd-11ea-8e60-4df8aa12f4c8.png)

You would have to wait for the owner of the organization to approve the request in order to see the repo in your list.

Since you would have already added Amplify as an authorized OAuth application in github, you would first need to revoke access for it, and try again. This time make sure to request access to the required organization.

Let me know if you have any questions.
