### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by fZara14** [aws-amplify/amplify-console#853]
**App Id**: d220ylt672nfhi
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by abhi7cr** [comment]
Hi @fZara14,

Could you go through the [troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html) and see if you are able to resolve it? Most of the cases, the domain activation fails because of a CNAME already exists exception. This error indicates there is already another amplify app / a CloudFront distribution you created personally, that has the same CNAME. You would need to delete the old amplify app / remove the CNAME from your CloudFront distribution, then delete your new domain, and retry adding it.

**Comment by ganipcanot** [comment]
Resolving due to age - re-open if you are still facing the issue!
