### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by leftbrainstuff** [aws-amplify/amplify-console#858]
**App Id**: d14wexddeeoirq
**Region**: ap-southeast-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Fails at domain activation with the following error message Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
I've just transferred the domain name between accounts and have had this issue in the previous account. I can see from the hosted zone info that there is a mismatch to what AWS Amplify expects.

**Comment by abhi7cr** [comment]
Hi @leftbrainstuff,

As the error suggests, the domain activation fails because of a CNAME already exists exception. This error indicates there is already another amplify app / a CloudFront distribution you created personally, that has the  same CNAME record (domain name) as the one you are trying to associate now. You would need to delete the old amplify app / remove the CNAME from your CloudFront distribution, then delete your new domain from the amplify app, and retry adding it.

**Comment by leftbrainstuff** [comment]
This issue still exists. There are no additional cloudfront distributions
or amplify apps.

**Comment by ganipcanot** [comment]
Looks like the domain associated to `d14wexddeeoirq` is active and working - please re-open the ticket if you are still experiencing issues.
