### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by pchauhan77** [aws-amplify/amplify-console#870]
**App Id**: d9jo3nhactls4
**Region**: ap-south-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by abhi7cr** [comment]
Hi @pchauhan77,

As the error suggests, the domain activation fails because of a CNAME already exists exception. This error indicates there is already another amplify app / a CloudFront distribution you created personally, that has the same CNAME record (domain name) as the one you are trying to associate now. You would need to delete the old amplify app / remove the CNAME from your CloudFront distribution, then delete your new domain from the amplify app, and retry adding it.

**Comment by pchauhan77** [comment]
i did but still getting this error

**Comment by ganipcanot** [comment]
@pchauhan77 It looks like you have since deleted the app `d9jo3nhactls4`.  Are you still experiencing an issue?

**Comment by ganipcanot** [comment]
Resolving due to age - re-open if you are still facing the issue!
