### ISSUE TITLE
Feature Branch Deploy stuck in "Verify"

### ISSUE THREAD

**Issue by tjspross** [aws-amplify/amplify-console#936]
** Please describe which feature you have a question about? **
My builds are getting stuck in verify. Maybe not a big deal, but I have to cancel the build eventually (I've seen it stay stuck for a couple of hours). Additionally, I hope I'm not being charged for "build time" as it is stuck

![image](https://user-images.githubusercontent.com/7739274/89469341-7509be00-d736-11ea-976e-2367b5eb8df7.png)

** Provide additional details**
App Id: d1ge9bft3fez35
Region: us-east-1

**Comment by kahdojay** [comment]
Hey @tjspross I can verify you were not billed for any of the time spent stuck in Verify, if you see unexpected values in your monthly bill you can always open a support case so we can take a closer look.

In the meantime we will need to investigate why your jobs are getting stuck in that step, let us know if you see a consistent pattern when this happens.

**Comment by tjspross** [comment]
Hi @kahdojay .

I just checked today. It looks like my builds ended up in "Failed". 

1. I've been seeing it consistently as of two or three builds ago. I see it on both my develop and master branch builds. Prior to that, I was seeing previews.
2. I do not see screenshot previews. When I go to the verify tab, it is totally blank.

**Comment by rubensavio** [comment]
Hi @kahdojay any updates on this bug. We are facing the same issue. Project is build & deployed but its under verify for more than 3 hours. Only an observation to share, while building we can see the github tree link on the console but sometimes the link toggles from our github link to an undefined link. 

Any help as our customers are unable to use the web app.

**Comment by aashishs101** [comment]
Hi @kahdojay we are facing the same issue as well, and after @rubensavio mentioned it, I noticed the same behavior with Github url.

**Comment by nucat176** [comment]
Hi @kahdojay - we are facing the exact same issue as well. Is there a way we are able to disable the verify step until is fixed?

**Comment by medmunds** [comment]
Same problem, appId dqjgvhvek1hpl us-east-1. After about 9 hours I eventually got a "Your build status is FAILED" notification email.

Don't know if it's relevant, because the previous build was back in July, but *all* previous successful builds in this project have a blue "Screenshots are temporarily disabled" message on the Verify step:
<img width="347" alt="previous build verify message" src="https://user-images.githubusercontent.com/639984/89683617-b53f7c80-d8ad-11ea-8ada-4bf8515ce999.png">

I have another project (appId d2zny4tezbjwg4 us-east-1) which is *not* getting stuck on verify, and it has always had successful screenshots in previous builds (back in July and today).

On the current builds, I too am seeing the "source repository" flash between the correct one and undefined:
<img width="561" alt="undefined source repository" src="https://user-images.githubusercontent.com/639984/89682987-7fe65f00-d8ac-11ea-8068-63bb29fd5d04.png">
... but I suspect this **may be an unrelated cosmetic problem in the console,** because my other project which isn't getting stuck *also* flashes its source repository to undefined while the build is running.

**Comment by Kethatril** [comment]
We are also having this issue, so far only on a specific branch. (AppID: d3u1atjgwp5fyy)
Not seeing any screenshots in the verify tab for the builds that get stuck.

**Comment by nhc-motosumo** [comment]
We seem to be having the same issue consistently on one of our branches. The previous steps execute swiftly without problems, but "Verify" stalls for a long time (many minutes, possibly hours) before failing. The deployed app seems to be working just fine, so I am not sure what the "Verify" step is unhappy with.

App Id:`dm197t2mo7xbv`
Region: `eu-west-1`
Branch: `feature/check_build_fix`
Build: Both 1 and 2.

**Comment by behrooziAWS** [comment]
We've identified an issue with screenshots timing out preventing the verify step from succeeding.  After putting in a fix it appears that at least 1 customer was able to successfully build on https://github.com/aws-amplify/amplify-console/issues/948 Can you try another build and let us know if it still gets stuck?

**Comment by medmunds** [comment]
@behrooziAWS that seemed to solve the "stuck in verify" problem for my project. Now the verify step runs for a few minutes, and then shows the "Screenshots are temporarily disabled message" and marks the build "SUCCEED".

<img width="347" alt="previous build verify message" src="https://user-images.githubusercontent.com/639984/89683617-b53f7c80-d8ad-11ea-8ada-4bf8515ce999.png">

(And I guess I've learned that "Screenshots are temporarily disabled" maybe actually means "screenshots timed out".)

**Comment by behrooziAWS** [comment]
Great that it worked @medmunds! We have have a known issue taking screenshots on sites where the network doesn't go idle or are media heavy.  It will no longer will block the verify, but you will see a message like the above while it is still an issue.

**Comment by nhc-motosumo** [comment]
Our build on the app mentioned above seem to work now. Thanks for looking into this!
